/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file contains all your LeetCode solution data for the interactive dashboard.
 */
const SOLUTIONS = {
  "Easy": [
    {
      "id": "0001",
      "title": "Two Sum",
      "difficulty": "Easy",
      "file": "Easy/0001_TwoSum.js",
      "content": "/**\n * Problem #1: Two Sum\n * \n * Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.\n * You may assume that each input would have exactly one solution, and you may not use the same element twice.\n * You can return the answer in any order.\n * \n * Example 1:\n * Input: nums = [2,7,11,15], target = 9\n * Output: [0,1]\n * Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].\n * \n * Example 2:\n * Input: nums = [3,2,4], target = 6\n * Output: [1,2]\n * \n * Example 3:\n * Input: nums = [3,3], target = 6\n * Output: [0,1]\n */\n\n/**\n * @param {number[]} nums\n * @param {number} target\n * @return {number[]}\n */\nvar twoSum = function(nums, target) {\n    var ans = [];\n    for(i=0;i<nums.length;i++){\n        for(j=i+1;j<nums.length;j++){\n            if(nums[i]+nums[j] == target){\n                ans.push(i,j);\n                break;\n            }\n        }\n    }\n    return ans;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0009",
      "title": "Palindrome Number",
      "difficulty": "Easy",
      "file": "Easy/0009_PalindromeNumber.js",
      "content": "/**\n * Problem #9: Palindrome Number\n * \n * Given an integer x, return true if x is a palindrome, and false otherwise.\n * \n * Example 1:\n * Input: x = 121\n * Output: true\n * Explanation: 121 reads as 121 from left to right and from right to left.\n * \n * Example 2:\n * Input: x = -121\n * Output: false\n * Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.\n * \n * Example 3:\n * Input: x = 10\n * Output: false\n * Explanation: Reads 01 from right to left. Therefore it is not a palindrome.\n */\n\n/**\n * @param {number} x\n * @return {boolean}\n */\nvar isPalindrome = function(x) {\n    if(x.toString() == x.toString().split('').reverse().join(''))\n        return true;\n    else \n        return false;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0013",
      "title": "Roman To Integer",
      "difficulty": "Easy",
      "file": "Easy/0013_RomanToInteger.js",
      "content": "/**\n * Problem #13: Roman to Integer\n * \n * Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.\n * Symbol       Value\n * I             1\n * V             5\n * X             10\n * L             50\n * C             100\n * D             500\n * M             1000\n * \n * For example, 2 is written as II in Roman numeral, just two ones added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.\n * \n * Roman numerals are usually written largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX. There are six instances where subtraction is used:\n * - I can be placed before V (5) and X (10) to make 4 and 9. \n * - X can be placed before L (50) and C (100) to make 40 and 90. \n * - C can be placed before D (500) and M (1000) to make 400 and 900.\n * \n * Example 1:\n * Input: s = \"III\"\n * Output: 3\n * \n * Example 2:\n * Input: s = \"LVIII\"\n * Output: 58\n * Explanation: L = 50, V = 5, III = 3.\n * \n * Example 3:\n * Input: s = \"MCMXCIV\"\n * Output: 1994\n * Explanation: M = 1000, CM = 900, XC = 90 and IV = 4.\n */\n\nconst romanMap = {\n  'I': 1,\n  'V': 5,\n  'X': 10,\n  'L': 50,\n  'C': 100,\n  'D': 500,\n  'M': 1000\n};\n\n/**\n * @param {string} s\n * @return {number}\n */\nvar romanToInt = function(s) {\n  let total = 0;\n\n  for (let i = 0; i < s.length; i++) {\n    // Check if current value < next value (subtraction case)\n    if (i + 1 < s.length && romanMap[s[i]] < romanMap[s[i + 1]]) {\n      total += romanMap[s[i + 1]] - romanMap[s[i]];\n      i++; // skip the next character since we used it\n    } else {\n      total += romanMap[s[i]];\n    }\n  }\n\n  return total;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0014",
      "title": "Longest Common Prefix",
      "difficulty": "Easy",
      "file": "Easy/0014_LongestCommonPrefix.js",
      "content": "/**\n * Problem #14: Longest Common Prefix\n * \n * Write a function to find the longest common prefix string amongst an array of strings.\n * If there is no common prefix, return an empty string \"\".\n * \n * Example 1:\n * Input: strs = [\"flower\",\"flow\",\"flight\"]\n * Output: \"fl\"\n * \n * Example 2:\n * Input: strs = [\"dog\",\"racecar\",\"car\"]\n * Output: \"\"\n * Explanation: There is no common prefix among the input strings.\n */\n\n/**\n * @param {string[]} strs\n * @return {string}\n */\nvar longestCommonPrefix = function (strs) {\n    if (strs.length == 0) return ``;\n\n    let prefix = strs[0];\n    for (i = 0; i < strs.length; i++) {\n        while (strs[i].indexOf(prefix) !== 0) {\n            prefix = prefix.slice(0, -1);\n            if (prefix === \"\") return \"\";\n        }\n    }\n    return prefix;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0020",
      "title": "Valid Parentheses",
      "difficulty": "Easy",
      "file": "Easy/0020_ValidParentheses.js",
      "content": "/**\n * Problem #20: Valid Parentheses\n * \n * Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.\n * \n * An input string is valid if:\n * 1. Open brackets must be closed by the same type of brackets.\n * 2. Open brackets must be closed in the correct order.\n * 3. Every closing bracket must have a corresponding open bracket of the same type.\n * \n * Example 1:\n * Input: s = \"()\"\n * Output: true\n * \n * Example 2:\n * Input: s = \"()[]{}\"\n * Output: true\n * \n * Example 3:\n * Input: s = \"(]\"\n * Output: false\n */\n\n/**\n * @param {string} s\n * @return {boolean}\n */\nvar isValid = function (s) {\n    if (s.length == 0) return false;\n\n    const stack = [];\n    const map = {\n        ')': '(',\n        '}': '{',\n        ']': '['\n    };\n    \n    for (let char of s) {\n        if (char === '(' || char === '{' || char === '[') {\n            stack.push(char);\n        } else {\n            if (stack.length === 0 || stack.pop() !== map[char]) {\n                return false;\n            }\n        }\n    }\n\n    return stack.length === 0;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0021",
      "title": "Merge Two Sorted Lists",
      "difficulty": "Easy",
      "file": "Easy/0021_MergeTwoSortedLists.js",
      "content": "/**\n * Problem #21: Merge Two Sorted Lists\n * \n * You are given the heads of two sorted linked lists list1 and list2.\n * Merge the two lists in a one sorted list. The list should be made by splicing together the nodes of the first two lists.\n * Return the head of the merged linked list.\n * \n * Example 1:\n * Input: list1 = [1,2,4], list2 = [1,3,4]\n * Output: [1,1,2,3,4,4]\n * \n * Example 2:\n * Input: list1 = [], list2 = []\n * Output: []\n * \n * Example 3:\n * Input: list1 = [], list2 = [0]\n * Output: [0]\n */\n\n/**\n * Definition for singly-linked list.\n * function ListNode(val, next) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.next = (next===undefined ? null : next)\n * }\n */\n/**\n * @param {ListNode} list1\n * @param {ListNode} list2\n * @return {ListNode}\n */\nvar mergeTwoLists = function(list1, list2) {\n    let dummy = new ListNode(-1);\n    let current = dummy;\n\n    while (list1 !== null && list2 !== null) {\n        if (list1.val <= list2.val) {\n            current.next = list1;\n            list1 = list1.next;\n        } else {\n            current.next = list2;\n            list2 = list2.next;\n        }\n        current = current.next;\n    }\n    current.next = list1 !== null ? list1 : list2;\n\n    return dummy.next;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0026",
      "title": "Remove Duplicates From Sorted Array",
      "difficulty": "Easy",
      "file": "Easy/0026_RemoveDuplicatesFromSortedArray.js",
      "content": "/**\n * Problem #26: Remove Duplicates from Sorted Array\n * \n * Given an integer array nums sorted in non-decreasing order, remove the duplicates in-place such that each unique element appears only once.\n * The relative order of the elements should be kept the same. Then return the number of unique elements in nums.\n * \n * Consider the number of unique elements of nums to be k, to get accepted, you need to do the following things:\n * 1. Modify the array nums such that the first k elements of nums contain the unique elements in the order they were initially in nums.\n * 2. Return k.\n * \n * Example 1:\n * Input: nums = [1,1,2]\n * Output: 2, nums = [1,2,_]\n * \n * Example 2:\n * Input: nums = [0,0,1,1,1,2,2,3,3,4]\n * Output: 5, nums = [0,1,2,3,4,_,_,_,_,_]\n */\n\n/**\n * @param {number[]} nums\n * @return {number}\n */\nvar removeDuplicates = function (nums) {\n    if (nums.length == 0) return 0;\n\n    var k = 0;\n\n    for (var i = 0; i < nums.length; i++) {\n        if (nums[k] != nums[i]) {\n            k++;\n            nums[k] = nums[i];\n        }\n    }\n    return k + 1;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0027",
      "title": "Remove Element",
      "difficulty": "Easy",
      "file": "Easy/0027_RemoveElement.js",
      "content": "/**\n * Problem #27: Remove Element\n * \n * Given an integer array nums and an integer val, remove all occurrences of val in nums in-place.\n * The order of the elements may be changed. Then return the number of elements in nums which are not equal to val.\n * \n * Consider the number of elements in nums which are not equal to val be k, to get accepted, you need to do the following things:\n * 1. Modify the array nums such that the first k elements of nums contain the elements which are not equal to val.\n * 2. Return k.\n * \n * Example 1:\n * Input: nums = [3,2,2,3], val = 3\n * Output: 2, nums = [2,2,_,_]\n * \n * Example 2:\n * Input: nums = [0,1,2,2,3,0,4,2], val = 2\n * Output: 5, nums = [0,1,4,0,3,_,_,_]\n */\n\n/**\n * @param {number[]} nums\n * @param {number} val\n * @return {number}\n */\nvar removeElement = function (nums, val) {\n    if (nums.length == 0) return 0;\n\n    var k = 0;\n    for (var i = 0; i < nums.length; i++) {\n        if (nums[i] !== val) {\n            nums[k] = nums[i]\n            k++;\n        }\n    }\n    return k;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0028",
      "title": "Find Index First Occurrence",
      "difficulty": "Easy",
      "file": "Easy/0028_FindIndexFirstOccurrence.js",
      "content": "/**\n * Problem #28: Find the Index of the First Occurrence in a String\n * \n * Given two strings needle and haystack, return the index of the first occurrence of needle in haystack, or -1 if needle is not part of haystack.\n * \n * Example 1:\n * Input: haystack = \"sadbutsad\", needle = \"sad\"\n * Output: 0\n * Explanation: \"sad\" occurs at index 0 and 6. The first occurrence is at index 0.\n * \n * Example 2:\n * Input: haystack = \"leetcode\", needle = \"leeto\"\n * Output: -1\n * Explanation: \"leeto\" did not occur in \"leetcode\", so we return -1.\n */\n\n/**\n * @param {string} haystack\n * @param {string} needle\n * @return {number}\n */\nvar strStr = function(haystack, needle) {\n    if (needle === \"\") return 0;\n    \n    for (let i = 0; i <= haystack.length - needle.length; i++) {\n        if (haystack[i] == needle[0]) {\n            if (haystack.slice(i, i + needle.length) == needle) {\n                return i;\n            }\n        }\n    }\n    return -1;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0035",
      "title": "Search Insert Position",
      "difficulty": "Easy",
      "file": "Easy/0035_SearchInsertPosition.js",
      "content": "/**\n * Problem #35: Search Insert Position\n * \n * Given a sorted array of distinct integers and a target value, return the index if the target is found.\n * If not, return the index where it would be if it were inserted in order.\n * You must write an algorithm with O(log n) runtime complexity.\n * \n * Example 1:\n * Input: nums = [1,3,5,6], target = 5\n * Output: 2\n * \n * Example 2:\n * Input: nums = [1,3,5,6], target = 2\n * Output: 1\n * \n * Example 3:\n * Input: nums = [1,3,5,6], target = 7\n * Output: 4\n */\n\n/**\n * @param {number[]} nums\n * @param {number} target\n * @return {number}\n */\nvar searchInsert = function(nums, target) {\n    if (nums.length == 0) return 0;\n    \n    for (let i = 0; i < nums.length; i++) {\n        if (nums[i] >= target) {\n            return i;\n        }\n    }\n    return nums.length;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0058",
      "title": "Length Of Last Word",
      "difficulty": "Easy",
      "file": "Easy/0058_LengthOfLastWord.js",
      "content": "/**\n * Problem #58: Length of Last Word\n * \n * Given a string s consisting of words and spaces, return the length of the last word in the string.\n * A word is a maximal substring consisting of non-space characters only.\n * \n * Example 1:\n * Input: s = \"Hello World\"\n * Output: 5\n * Explanation: The last word is \"World\" with length 5.\n * \n * Example 2:\n * Input: s = \"   fly me   to   the moon  \"\n * Output: 4\n * Explanation: The last word is \"moon\" with length 4.\n * \n * Example 3:\n * Input: s = \"luffy is still joyboy\"\n * Output: 6\n * Explanation: The last word is \"joyboy\" with length 6.\n */\n\n/**\n * @param {string} s\n * @return {number}\n */\nvar lengthOfLastWord = function (s) {\n    let length = 0;\n    let i = s.length - 1;\n\n    // Skip trailing spaces\n    while (i >= 0 && s[i] === \" \") {\n        i--;\n    }\n\n    // Count characters of the last word\n    while (i >= 0 && s[i] !== \" \") {\n        length++;\n        i--;\n    }\n\n    return length;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0066",
      "title": "Plus One",
      "difficulty": "Easy",
      "file": "Easy/0066_PlusOne.js",
      "content": "/**\n * Problem #66: Plus One\n * \n * You are given a large integer represented as an integer array digits, where each digits[i] is the ith digit of the integer. \n * The digits are ordered from most significant to least significant in left-to-right order. \n * The large integer does not contain any leading 0's, except for the number 0 itself.\n * \n * Increment the large integer by one and return the resulting array of digits.\n * \n * Example 1:\n * Input: digits = [1,2,3]\n * Output: [1,2,4]\n * Explanation: The array represents the integer 123. Incrementing by one gives 123 + 1 = 124. Thus, the result should be [1,2,4].\n * \n * Example 2:\n * Input: digits = [4,3,2,1]\n * Output: [4,3,2,2]\n * Explanation: The array represents the integer 4321. Incrementing by one gives 4321 + 1 = 4322. Thus, the result should be [4,3,2,2].\n * \n * Example 3:\n * Input: digits = [9]\n * Output: [1,0]\n * Explanation: The array represents the integer 9. Incrementing by one gives 9 + 1 = 10. Thus, the result should be [1,0].\n */\n\n/**\n * @param {number[]} digits\n * @return {number[]}\n */\nvar plusOne = function(digits) {\n    for (let i = digits.length - 1; i >= 0; i--) {\n        if (digits[i] < 9) {\n            digits[i]++;\n            return digits;\n        }\n        digits[i] = 0;\n    }\n\n    // If we're here, it means all digits were 9 (e.g., [9,9,9] -> [0,0,0])\n    digits.unshift(1);\n    return digits;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0067",
      "title": "Add Binary",
      "difficulty": "Easy",
      "file": "Easy/0067_AddBinary.js",
      "content": "/**\n * Problem #67: Add Binary\n * \n * Given two binary strings a and b, return their sum as a binary string.\n * \n * Example 1:\n * Input: a = \"11\", b = \"1\"\n * Output: \"100\"\n * \n * Example 2:\n * Input: a = \"1010\", b = \"1011\"\n * Output: \"10101\"\n */\n\n/**\n * @param {string} a\n * @param {string} b\n * @return {string}\n */\nvar addBinary = function (a, b) {\n    let i = a.length - 1;\n    let j = b.length - 1;\n    let carry = 0;\n    let result = \"\";\n\n    while (i >= 0 || j >= 0 || carry) {\n        let sum = carry;\n\n        if (i >= 0) sum += +a[i--];\n        if (j >= 0) sum += +b[j--];\n\n        result = (sum % 2) + result; // add bit\n        carry = Math.floor(sum / 2); // carry\n    }\n    return result;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0069",
      "title": "Sqrt X",
      "difficulty": "Easy",
      "file": "Easy/0069_SqrtX.js",
      "content": "/**\n * Problem #69: Sqrt(x)\n * \n * Given a non-negative integer x, return the square root of x rounded down to the nearest integer. \n * The returned integer should be non-negative as well.\n * You must not use any built-in exponent function or operator.\n * \n * Example 1:\n * Input: x = 4\n * Output: 2\n * Explanation: The square root of 4 is 2, so we return 2.\n * \n * Example 2:\n * Input: x = 8\n * Output: 2\n * Explanation: The square root of 8 is 2.82842..., and since we round it down to the nearest integer, 2 is returned.\n */\n\n/**\n * @param {number} x\n * @return {number}\n */\nvar mySqrt = function(x) {\n    if (x < 2) return x;\n\n    let right = x;\n    let left = 1;\n    let ans = 0;\n\n    while (left <= right) {\n        let mid = Math.floor((left + right) / 2);\n        let temp = mid * mid;\n        if (temp == x) {\n            return mid;\n        } else if (temp < x) {\n            ans = mid;\n            left = mid + 1;\n        } else {\n            right = mid - 1;\n        }\n    }\n    return ans;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0070",
      "title": "Climbing Stairs",
      "difficulty": "Easy",
      "file": "Easy/0070_ClimbingStairs.js",
      "content": "/**\n * Problem #70: Climbing Stairs\n * \n * You are climbing a staircase. It takes n steps to reach the top.\n * Each time you can either climb 1 or 2 steps. \n * In how many distinct ways can you climb to the top?\n * \n * Example 1:\n * Input: n = 2\n * Output: 2\n * Explanation: There are two ways to climb to the top.\n * 1. 1 step + 1 step\n * 2. 2 steps\n * \n * Example 2:\n * Input: n = 3\n * Output: 3\n * Explanation: There are three ways to climb to the top.\n * 1. 1 step + 1 step + 1 step\n * 2. 1 step + 2 steps\n * 3. 2 steps + 1 step\n * \n * Constraints:\n * 1 <= n <= 45\n */\n\n/**\n * @param {number} n\n * @return {number}\n */\nvar climbStairs = function (n) {\n    // Base cases\n    if (n < 3) return n;\n\n    // We only need the last two values (Fibonacci approach)\n    let p1 = 2; // ways to reach the previous step (n-1)\n    let p2 = 1; // ways to reach the step before that (n-2)\n    \n    for (let i = 3; i <= n; i++) {\n        let current = p1 + p2;\n        p2 = p1;\n        p1 = current;\n    }\n\n    return p1;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0083",
      "title": "Remove Duplicates From Sorted List",
      "difficulty": "Easy",
      "file": "Easy/0083_RemoveDuplicatesFromSortedList.js",
      "content": "/**\n * Problem #83: Remove Duplicates from Sorted List\n * \n * Given the head of a sorted linked list, delete all duplicates such that each element appears only once. \n * Return the linked list sorted as well.\n * \n * Example 1:\n * Input: head = [1,1,2]\n * Output: [1,2]\n * \n * Example 2:\n * Input: head = [1,1,2,3,3]\n * Output: [1,2,3]\n * \n * Constraints:\n * - The number of nodes in the list is in the range [0, 300].\n * - -100 <= Node.val <= 100\n * - The list is guaranteed to be sorted in ascending order.\n */\n\n/**\n * Definition for singly-linked list.\n * function ListNode(val, next) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.next = (next===undefined ? null : next)\n * }\n */\n\n/**\n * @param {ListNode} head\n * @return {ListNode}\n */\nvar deleteDuplicates = function(head) {\n    let current = head;\n\n    while (current && current.next) {\n        if (current.val === current.next.val) {\n            // Found a duplicate, skip the next node\n            current.next = current.next.next; \n        } else {\n            // Move to the next unique node\n            current = current.next; \n        }\n    }\n\n    return head;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0088",
      "title": "Merge Sorted Array",
      "difficulty": "Easy",
      "file": "Easy/0088_MergeSortedArray.js",
      "content": "/**\n * Problem #88: Merge Sorted Array\n * \n * You are given two integer arrays nums1 and nums2, sorted in non-decreasing order, \n * and two integers m and n, representing the number of elements in nums1 and nums2 respectively.\n * \n * Merge nums1 and nums2 into a single array sorted in non-decreasing order.\n * \n * The final sorted array should not be returned by the function, but instead be stored inside the array nums1. \n * To accommodate this, nums1 has a length of m + n, where the first m elements denote the elements that \n * should be merged, and the last n elements are set to 0 and should be ignored. nums2 has a length of n.\n * \n * Example 1:\n * Input: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3\n * Output: [1,2,2,3,5,6]\n * \n * Example 2:\n * Input: nums1 = [1], m = 1, nums2 = [], n = 0\n * Output: [1]\n * \n * Example 3:\n * Input: nums1 = [0], m = 0, nums2 = [1], n = 1\n * Output: [1]\n */\n\n/**\n * @param {number[]} nums1\n * @param {number} m\n * @param {number[]} nums2\n * @param {number} n\n * @return {void} Do not return anything, modify nums1 in-place instead.\n */\nvar merge = function (nums1, m, nums2, n) {\n    let i = m - 1;        // last element of nums1\n    let j = n - 1;        // last element of nums2\n    let k = m + n - 1;    // last position of nums1\n\n    while (j >= 0) {\n        if (i >= 0 && nums1[i] > nums2[j]) {\n            nums1[k] = nums1[i];\n            i--;\n        } else {\n            nums1[k] = nums2[j];\n            j--;\n        }\n        k--;\n    }\n};\n",
      "language": "javascript"
    },
    {
      "id": "0094",
      "title": "Binary Tree Inorder Traversal",
      "difficulty": "Easy",
      "file": "Easy/0094_BinaryTreeInorderTraversal.js",
      "content": "/**\n * Problem #94: Binary Tree Inorder Traversal\n * \n * Given the root of a binary tree, return the inorder traversal of its nodes' values.\n * \n * Example 1:\n * Input: root = [1,null,2,3]\n * Output: [1,3,2]\n * \n * Example 2:\n * Input: root = []\n * Output: []\n * \n * Example 3:\n * Input: root = [1]\n * Output: [1]\n * \n * Constraints:\n * - The number of nodes in the tree is in the range [0, 100].\n * - -100 <= Node.val <= 100\n */\n\n/**\n * Definition for a binary tree node.\n * function TreeNode(val, left, right) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.left = (left===undefined ? null : left)\n *     this.right = (right===undefined ? null : right)\n * }\n */\n\n/**\n * @param {TreeNode} root\n * @return {number[]}\n */\nvar inorderTraversal = function (root) {\n    let result = [];\n\n    /**\n     * Helper function for recursive depth-first search\n     */\n    var dfs = function (node) {\n        if (node === null) return;\n        \n        // Traverse left subtree\n        dfs(node.left);\n        \n        // Visit root node\n        result.push(node.val);\n        \n        // Traverse right subtree\n        dfs(node.right);\n    }\n    \n    dfs(root);\n    return result;\n};\n",
      "language": "javascript"
    },
    {
      "id": "0100",
      "title": "Same Tree",
      "difficulty": "Easy",
      "file": "Easy/0100_SameTree.js",
      "content": "/**\n * Problem #100: Same Tree\n * \n * Given the roots of two binary trees p and q, write a function to check if they are the same or not.\n * Two binary trees are considered the same if they are structurally identical, and the nodes have the same value.\n * \n * Example 1:\n * Input: p = [1,2,3], q = [1,2,3]\n * Output: true\n * \n * Example 2:\n * Input: p = [1,2], q = [1,null,2]\n * Output: false\n * \n * Example 3:\n * Input: p = [1,2,1], q = [1,1,2]\n * Output: false\n * \n * Constraints:\n * - The number of nodes in both trees is in the range [0, 100].\n * - -10^4 <= Node.val <= 10^4\n */\n\n/**\n * Definition for a binary tree node.\n * function TreeNode(val, left, right) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.left = (left===undefined ? null : left)\n *     this.right = (right===undefined ? null : right)\n * }\n */\n\n/**\n * @param {TreeNode} p\n * @param {TreeNode} q\n * @return {boolean}\n */\nvar isSameTree = function (p, q) {\n    // If both nodes are null, the trees are the same at this position\n    if (!p && !q) return true;\n    \n    // If one node is null and the other is not, they are different\n    if (!p || !q) return false;\n\n    // If values are different, they are different\n    if (p.val != q.val) return false;\n\n    // Recursively check left and right subtrees\n    return isSameTree(p.left, q.left) && isSameTree(p.right, q.right);\n};\n",
      "language": "javascript"
    },
    {
      "id": "0101",
      "title": "Symmetric Tree",
      "difficulty": "Easy",
      "file": "Easy/0101_SymmetricTree.js",
      "content": "/**\n * Problem #101: Symmetric Tree\n * \n * Given the root of a binary tree, check whether it is a mirror of itself (i.e., symmetric around its center).\n * \n * Example 1:\n * Input: root = [1,2,2,3,4,4,3]\n * Output: true\n * \n * Example 2:\n * Input: root = [1,2,2,null,3,null,3]\n * Output: false\n * \n * Constraints:\n * - The number of nodes in the tree is in the range [1, 1000].\n * - -100 <= Node.val <= 100\n */\n\n/**\n * Definition for a binary tree node.\n * function TreeNode(val, left, right) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.left = (left===undefined ? null : left)\n *     this.right = (right===undefined ? null : right)\n * }\n */\n\n/**\n * @param {TreeNode} root\n * @return {boolean}\n */\nvar isSymmetric = function (root) {\n    if (!root) return true;\n\n    /**\n     * Helper function to check if two subtrees are mirrors of each other\n     */\n    let isMirror = function (left, right) {\n        // Both nodes are null\n        if (left == null && right == null) return true;\n        \n        // Only one node is null or values differ\n        if (!left || !right) return false;\n        if (left.val != right.val) return false;\n        \n        // Check if outer children and inner children are mirrors\n        return isMirror(left.left, right.right) && isMirror(left.right, right.left);\n    }\n\n    return isMirror(root.left, root.right);\n};\n",
      "language": "javascript"
    },
    {
      "id": "0104",
      "title": "Maximum Depth Of Binary Tree",
      "difficulty": "Easy",
      "file": "Easy/0104_MaximumDepthOfBinaryTree.js",
      "content": "/**\r\n * Problem #104: Maximum Depth of Binary Tree\r\n *\r\n * Given the root of a binary tree, return its maximum depth.\r\n *\r\n * A binary tree's maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.\r\n *\r\n * Example 1:\r\n * Input: root = [3,9,20,null,null,15,7]\r\n * Output: 3\r\n *\r\n * Example 2:\r\n * Input: root = [1,null,2]\r\n * Output: 2\r\n *\r\n * Constraints:\r\n * - The number of nodes in the tree is in the range [0, 10^4].\r\n * - -100 <= Node.val <= 100\r\n */\r\n\r\n/**\r\n * Definition for a binary tree node.\r\n * function TreeNode(val, left, right) {\r\n *     this.val = (val===undefined ? 0 : val)\r\n *     this.left = (left===undefined ? null : left)\r\n *     this.right = (right===undefined ? null : right)\r\n * }\r\n */\r\n\r\n/**\r\n * @param {TreeNode} root\r\n * @return {number}\r\n */\r\nvar maxDepth = function(root) {\r\n    if (root === null) return 0;\r\n\r\n    let leftDepth = maxDepth(root.left);\r\n    let rightDepth = maxDepth(root.right);\r\n\r\n    return Math.max(leftDepth, rightDepth) + 1;\r\n};",
      "language": "javascript"
    },
    {
      "id": "0108",
      "title": "Convert Sorted Array To Binary Search Tree",
      "difficulty": "Easy",
      "file": "Easy/0108_ConvertSortedArrayToBinarySearchTree.js",
      "content": "/**\r\n * Problem 108: Convert Sorted Array to Binary Search Tree\r\n * Difficulty: Easy\r\n *\r\n * Given an integer array nums where elements are sorted in ascending order,\r\n * convert it to a height-balanced binary search tree.\r\n *\r\n * Example 1:\r\n * Input: nums = [-10,-3,0,5,9]\r\n * Output: [0,-3,9,-10,null,5]\r\n *\r\n * Example 2:\r\n * Input: nums = [1,3]\r\n * Output: [3,1]\r\n *\r\n * Constraints:\r\n * - 1 <= nums.length <= 10^4\r\n * - -10^4 <= nums[i] <= 10^4\r\n * - nums is sorted in a strictly increasing order.\r\n *\r\n * Time Complexity: O(n)\r\n * Space Complexity: O(log n) recursion stack for tree depth.\r\n */\r\n\r\n/**\r\n * Definition for a binary tree node.\r\n * function TreeNode(val, left, right) {\r\n *     this.val = (val===undefined ? 0 : val)\r\n *     this.left = (left===undefined ? null : left)\r\n *     this.right = (right===undefined ? null : right)\r\n * }\r\n */\r\n/**\r\n * @param {number[]} nums\r\n * @return {TreeNode}\r\n */\r\nvar sortedArrayToBST = function (nums) {\r\n  function createNode(start, end) {\r\n    if (start > end) return null;\r\n\r\n    const mid = Math.floor((start + end) / 2);\r\n    const node = new TreeNode(nums[mid]);\r\n\r\n    node.left = createNode(start, mid - 1);\r\n    node.right = createNode(mid + 1, end);\r\n\r\n    return node;\r\n  }\r\n\r\n  return createNode(0, nums.length - 1);\r\n};\r\n",
      "language": "javascript"
    },
    {
      "id": "0121",
      "title": "Best Time To Buy And Sell Stock",
      "difficulty": "Easy",
      "file": "Easy/0121_BestTimeToBuyAndSellStock.js",
      "content": "/**\r\n * Problem 121: Best Time to Buy and Sell Stock\r\n * Difficulty: Easy\r\n *\r\n * You are given an array prices where prices[i] is the price of a given stock on the i-th day.\r\n * You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.\r\n *\r\n * Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.\r\n *\r\n * Example:\r\n * Input: prices = [7,1,5,3,6,4]\r\n * Output: 5\r\n *\r\n * Constraints:\r\n * - 1 <= prices.length <= 10^5\r\n * - 0 <= prices[i] <= 10^4\r\n *\r\n * Time Complexity: O(n)\r\n * Space Complexity: O(1)\r\n */\r\n\r\n/**\r\n * @param {number[]} prices\r\n * @return {number}\r\n */\r\nvar maxProfit = function (prices) {\r\n  let minPrice = prices[0];\r\n  let profit = 0;\r\n\r\n  for (const price of prices) {\r\n    if (price < minPrice) {\r\n      minPrice = price;\r\n    } else if (price - minPrice > profit) {\r\n      profit = price - minPrice;\r\n    }\r\n  }\r\n\r\n  return profit;\r\n};\r\n",
      "language": "javascript"
    },
    {
      "id": "175",
      "title": "Combine Two Tables",
      "difficulty": "Easy",
      "file": "SQL/Easy/0175_CombineTwoTables.sql",
      "content": "-- Problem 175: Combine Two Tables\r\n-- Difficulty: Easy\r\n--\r\n-- Write a SQL query to report the first name, last name, city and state of each person in the Person table.\r\n-- If the address of a person is not present in the Address table, report null instead.\r\n--\r\n-- Table: Person\r\n-- +-------------+---------+\r\n-- | Column Name | Type    |\r\n-- +-------------+---------+\r\n-- | PersonId    | int     |\r\n-- | FirstName   | varchar |\r\n-- | LastName    | varchar |\r\n-- +-------------+---------+\r\n-- PersonId is the primary key for this table.\r\n--\r\n-- Table: Address\r\n-- +-------------+---------+\r\n-- | Column Name | Type    |\r\n-- +-------------+---------+\r\n-- | AddressId   | int     |\r\n-- | PersonId    | int     |\r\n-- | City        | varchar |\r\n-- | State       | varchar |\r\n-- +-------------+---------+\r\n-- AddressId is the primary key for this table.\r\n--\r\n-- Solution: Use LEFT JOIN to combine tables, ensuring all persons are included even if they have no address.\r\n\r\n/* Write your MySQL query statement below */\r\nSELECT\r\n    p.firstName,\r\n    p.lastName,\r\n    a.city,\r\n    a.state\r\nFROM\r\n    Person p\r\nLEFT JOIN\r\n    Address a\r\nON\r\n    p.PersonId = a.PersonId;",
      "language": "sql"
    }
  ],
  "Medium": [
    {
      "id": "2",
      "title": "Add Two Numbers",
      "difficulty": "Medium",
      "file": "Medium/0002_AddTwoNumbers.js",
      "content": "/**\n * Problem #2: Add Two Numbers (Medium)\n * \n * You are given two non-empty linked lists representing two non-negative integers. \n * The digits are stored in reverse order, and each of their nodes contains a single digit. \n * Add the two numbers and return the sum as a linked list.\n * \n * You may assume the two numbers do not contain any leading zero, except the number 0 itself.\n * \n * Example 1:\n * Input: l1 = [2,4,3], l2 = [5,6,4]\n * Output: [7,0,8]\n * Explanation: 342 + 465 = 807.\n * \n * Example 2:\n * Input: l1 = [0], l2 = [0]\n * Output: [0]\n * \n * Example 3:\n * Input: l1 = [9,9,9,9,9,9,9], l2 = [9,9,9,9]\n * Output: [8,9,9,9,0,0,0,1]\n * \n * Constraints:\n * - The number of nodes in each linked list is in the range [1, 100].\n * - 0 <= Node.val <= 9\n * - It is guaranteed that the list represents a number that does not have leading zeros.\n */\n\n/**\n * Definition for singly-linked list.\n * function ListNode(val, next) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.next = (next===undefined ? null : next)\n * }\n */\n\n/**\n * @param {ListNode} l1\n * @param {ListNode} l2\n * @return {ListNode}\n */\nvar addTwoNumbers = function (l1, l2) {\n    let dummy = new ListNode(0);\n    let current = dummy;\n    let carry = 0;\n\n    while (l1 || l2 || carry > 0) {\n        let val1 = l1 ? l1.val : 0;\n        let val2 = l2 ? l2.val : 0;\n        let sum = val1 + val2 + carry;\n\n        // Calculate carry for the next sum\n        carry = Math.floor(sum / 10);\n        \n        // Create new node with the current digit\n        current.next = new ListNode(sum % 10);\n        current = current.next;\n        \n        // Advance the pointers\n        l1 = l1 ? l1.next : null;\n        l2 = l2 ? l2.next : null;\n    }\n    \n    return dummy.next;\n};\n",
      "language": "javascript"
    },
    {
      "id": "3",
      "title": "Longest Substring Without Repeating Characters",
      "difficulty": "Medium",
      "file": "Medium/0003_LongestSubstringWithoutRepeatingCharacters.js",
      "content": "/**\n * Problem #3: Longest Substring Without Repeating Characters (Medium)\n * \n * Given a string s, find the length of the longest substring without repeating characters.\n * \n * Example 1:\n * Input: s = \"abcabcbb\"\n * Output: 3\n * Explanation: The answer is \"abc\", with the length of 3.\n * \n * Example 2:\n * Input: s = \"bbbbb\"\n * Output: 1\n * \n * Example 3:\n * Input: s = \"pwwkew\"\n * Output: 3\n * Explanation: The answer is \"wke\", with the length of 3.\n * \n * Constraints:\n * - 0 <= s.length <= 5 * 10^4\n * - s consists of English letters, digits, symbols and spaces.\n * \n * ---\n * ### Execution Flow Table (Example: s = \"pwwkew\")\n * \n * | Step | Char | Start | i | Action | charSet | maxLength |\n * | :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n * | 0 | 'p' | 0 | 0 | Add 'p' | {p} | 1 |\n * | 1 | 'w' | 0 | 1 | Add 'w' | {p, w} | 2 |\n * | 2 | 'w' | 0 | 2 | Duplicate 'w'! Shrink window | {p, w} -> {w} | 2 |\n * | 3 | 'k' | 2 | 3 | Add 'k' | {w, k} | 2 |\n * | 4 | 'e' | 2 | 4 | Add 'e' | {w, k, e} | 3 |\n * | 5 | 'w' | 2 | 5 | Duplicate 'w'! Shrink window | {k, e, w} | 3 |\n */\n\n/**\n * @param {string} s\n * @return {number}\n */\nvar lengthOfLongestSubstring = function (s) {\n    if (s.length < 2) return s.length;\n\n    let maxLength = 0;\n    let start = 0;\n    let charSet = new Set();\n\n    for (let i = 0; i < s.length; i++) {\n        // Sliding Window logic: \n        // If we find a duplicate, shrink the window from the left\n        while (charSet.has(s[i])) {\n            charSet.delete(s[start]);\n            start++;\n        }\n        \n        // Add current character and calculate max length\n        charSet.add(s[i]);\n        maxLength = Math.max(maxLength, i - start + 1);\n    }\n    \n    return maxLength;\n};\n",
      "language": "javascript"
    },
    {
      "id": "5",
      "title": "Longest Palindromic Substring",
      "difficulty": "Medium",
      "file": "Medium/0005_LongestPalindromicSubstring.js",
      "content": "/**\n * Problem #5: Longest Palindromic Substring (Medium)\n * \n * Given a string s, return the longest palindromic substring in s.\n * \n * Example 1:\n * Input: s = \"babad\"\n * Output: \"bab\"\n * Explanation: \"aba\" is also a valid answer.\n * \n * Example 2:\n * Input: s = \"cbbd\"\n * Output: \"bb\"\n * \n * Constraints:\n * - 1 <= s.length <= 1000\n * - s consists of only digits and English letters.\n * \n * ---\n * ### Execution Flow Table (Example: s = \"babad\")\n * \n * | Step | Index | Char | Expand (Odd) | Expand (Even) | Found Palindrome | State (Start, End) | Substring |\n * | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n * | 0 | 0 | 'b' | \"b\" (1) | \"\" (0) | \"b\" | (0, 0) | \"b\" |\n * | 1 | 1 | 'a' | \"bab\" (3) | \"\" (0) | \"bab\" | (0, 2) | \"bab\" |\n * | 2 | 2 | 'b' | \"aba\" (3) | \"\" (0) | \"aba\" (equal len) | (0, 2) | \"bab\" |\n * | 3 | 3 | 'a' | \"a\" (1) | \"\" (0) | - | (0, 2) | \"bab\" |\n * | 4 | 4 | 'd' | \"d\" (1) | \"\" (0) | - | (0, 2) | \"bab\" |\n * \n * Final Result: \"bab\" (or \"aba\")\n */\n\n/**\n * @param {string} s\n * @return {string}\n */\nvar longestPalindrome = function (s) {\n    if (s.length < 2) return s;\n\n    let start = 0;\n    let end = 0;\n\n    /**\n     * Helper to expand outwards from a center and return the length of the palindrome\n     */\n    let checkAround = function (s, left, right) {\n        while (left >= 0 && right < s.length && s[left] === s[right]) {\n            left--;\n            right++;\n        }\n        // Result is length: right - left - 1\n        return right - left - 1;\n    }\n\n    for (let i = 0; i < s.length; i++) {\n        // Case 1: Centered at i (odd length, e.g. \"aba\")\n        let len1 = checkAround(s, i, i);\n        \n        // Case 2: Centered between i and i+1 (even length, e.g. \"abba\")\n        let len2 = checkAround(s, i, i + 1);\n        \n        // Pick the best of the two\n        let len = Math.max(len1, len2);\n        \n        // Update the best start/end indices if we found a longer one\n        if (len > end - start) {\n            start = i - Math.floor((len - 1) / 2);\n            end = i + Math.floor(len / 2);\n        }\n    }\n\n    return s.slice(start, end + 1);\n};\n",
      "language": "javascript"
    },
    {
      "id": "6",
      "title": "Zigzag Conversion",
      "difficulty": "Medium",
      "file": "Medium/0006_ZigzagConversion.js",
      "content": "/**\n * Problem #6: Zigzag Conversion (Medium)\n * \n * The string \"PAYPALISHIRING\" is written in a zigzag pattern on a given number of rows like this:\n * P   A   H   N\n * A P L S I I G\n * Y   I   R\n * \n * And then read line by line: \"PAHNAPLSIIGYIR\"\n * \n * Write the code that will take a string and make this conversion given a number of rows.\n * \n * Example 1:\n * Input: s = \"PAYPALISHIRING\", numRows = 3\n * Output: \"PAHNAPLSIIGYIR\"\n * \n * Example 2:\n * Input: s = \"PAYPALISHIRING\", numRows = 4\n * Output: \"PINALSIGYAHRPI\"  (Wait, original is PINALSIGYAHRPI)\n * \n * Constraints:\n * - 1 <= s.length <= 1000\n * - s consists of English letters (lower-case and upper-case), ',' and '.'.\n * - 1 <= numRows <= 1000\n * \n * ---\n * ### Execution Flow Table (Example: s = \"PAYPAL\", numRows = 3)\n * \n * | Step | s[i] | temp (Row) | direction | arr Status |\n * | :--- | :--- | :---       | :---      | :--- |\n * | 0 | 'P' | 0 | 1 (Down) | `arr[0]=\"P\"` |\n * | 1 | 'A' | 1 | 1 (Down) | `arr[1]=\"A\"` |\n * | 2 | 'Y' | 2 | -1 (Up) | `arr[2]=\"Y\"` (Hit bottom limit) |\n * | 3 | 'P' | 1 | -1 (Up) | `arr[1]=\"AP\"` |\n * | 4 | 'A' | 0 | 1 (Down) | `arr[0]=\"PA\"` (Hit top limit) |\n * | 5 | 'L' | 1 | 1 (Down) | `arr[1]=\"APL\"` |\n * | 6 | -   | - | -        | **Result:** \"PA\" + \"APL\" + \"Y\" = \"PAAPLY\" |\n */\n\n/**\n * @param {string} s\n * @param {number} numRows\n * @return {string}\n */\nvar convert = function (s, numRows) {\n    if (numRows === 1) return s;\n    let arr = [];\n    let direction = 1; // -1->up  1->down \n    let temp = 0;\n\n    for (let i = 0; i < s.length; i++) {\n        if (!arr[temp]) arr[temp] = \"\";\n        arr[temp] = arr[temp] + s[i];\n        temp += direction;\n        if (temp === 0 || temp === numRows - 1) {\n            direction *= -1;\n        }\n    }\n\n    return arr.join(\"\");\n};\n",
      "language": "javascript"
    },
    {
      "id": "7",
      "title": "Reverse Integer",
      "difficulty": "Medium",
      "file": "Medium/0007_ReverseInteger.js",
      "content": "/**\n * Problem #7: Reverse Integer (Medium)\n * \n * Given a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range [-2^31, 2^31 - 1], then return 0.\n * \n * Assume the environment does not allow you to store 64-bit integers (signed or unsigned).\n * \n * Example 1:\n * Input: x = 123\n * Output: 321\n * \n * Example 2:\n * Input: x = -123\n * Output: -321\n * \n * Example 3:\n * Input: x = 120\n * Output: 21\n * \n * Constraints:\n * - -2^31 <= x <= 2^31 - 1\n * \n * ---\n * ### Execution Flow Table (Example: x = 123)\n * \n * | Step | result | temp | temp % 10 | Action |\n * | :--- | :--- | :--- | :--- | :--- |\n * | 0 | 0 | 123 | - | Initialize variables |\n * | 1 | 3 | 12 | 3 | Add 3 to result |\n * | 2 | 32 | 1 | 2 | Add 2 to result |\n * | 3 | 321 | 0 | 1 | Add 1 to result |\n * | 4 | 321 | 0 | - | Return result (in bounds) |\n */\n\n/**\n * @param {number} x\n * @return {number}\n */\nvar reverse = function (x) {\n    let result = 0;\n    let temp = x;\n    while (temp) {\n        result = result * 10 + (temp % 10);\n        temp = Math.trunc(temp / 10);\n    }\n    if (result > 2147483647 || result < -2147483648) return 0;\n    return result;\n};\n",
      "language": "javascript"
    },
    {
      "id": "8",
      "title": "String to Integer",
      "difficulty": "atoi",
      "file": "Medium/0008_StringToIntegerAtoi.js",
      "content": "/**\n * Problem #8: String to Integer (atoi) (Medium)\n * \n * Implement the myAtoi(string s) function, which converts a string to a 32-bit signed integer (similar to C/C++'s atoi function).\n * \n * The algorithm for myAtoi(string s) is as follows:\n * 1. Read in and ignore any leading whitespace.\n * 2. Check if the next character (if not already at the end of the string) is '-' or '+'. Read this character in if it is either. This determines if the final result is negative or positive respectively. Assume the result is positive if neither is present.\n * 3. Read in next the characters until the next non-digit character or the end of the input is reached. The rest of the string is ignored.\n * 4. Convert these digits into an integer (i.e. \"123\" -> 123, \"0032\" -> 32). If no digits were read, then the integer is 0. Change the sign as necessary (from step 2).\n * 5. If the integer is out of the 32-bit signed integer range [-2^31, 2^31 - 1], then clamp the integer so that it remains in the range. Specifically, integers less than -2^31 should be clamped to -2^31, and integers greater than 2^31 - 1 should be clamped to 2^31 - 1.\n * 6. Return the integer as the final result.\n * \n * Example 1:\n * Input: s = \"42\"\n * Output: 42\n * \n * Example 2:\n * Input: s = \"   -42\"\n * Output: -42\n * \n * Example 3:\n * Input: s = \"4193 with words\"\n * Output: 4193\n * \n * Constraints:\n * - 0 <= s.length <= 200\n * - s consists of English letters (lower-case and upper-case), digits (0-9), ' ', '+', '-', and '.'.\n * \n * ---\n * ### Execution Flow Table (Example: s = \"   -42\")\n * \n * | Step | s[i] | Phase          | result | isN |\n * | :--- | :--- | :---           | :---   | :--- |\n * | 0 | ' ' | Ignore spaces  | 0 | 1 |\n * | 1 | '-' | Sign Check     | 0 | -1 |\n * | 2 | '4' | Parsing Digits | 4 | -1 |\n * | 3 | '2' | Parsing Digits | 42 | -1 |\n * | 4 | -   | Complete       | 42 | -1 | => Result: -42\n */\n\n/**\n * @param {string} s\n * @return {number}\n */\nvar myAtoi = function (s) {\n    let result = 0;\n    let i = 0;\n    let isN = 1;\n    while (s[i] === \" \") {\n        i++;\n    }\n    if (s[i] == \"-\" || s[i] == \"+\") {\n        if (s[i] == \"-\") isN = -1;\n        i++;\n    }\n\n    while (s[i] >= \"0\" && s[i] <= \"9\") {\n        result = result * 10 + +s[i];\n        i++;\n    }\n\n    // Clamp the integer bounding\n    if (result > 2147483647 || result < -2147483648) {\n        if (isN > 0) return 2147483647;\n        else return -2147483648;\n    }\n    \n    return result * isN;\n};\n",
      "language": "javascript"
    },
    {
      "id": "11",
      "title": "Container With Most Water",
      "difficulty": "Medium",
      "file": "Medium/0011_ContainerWithMostWater.js",
      "content": "/**\n * Problem #11: Container With Most Water (Medium)\n * \n * You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]).\n * Find two lines that together with the x-axis form a container, such that the container contains the most water.\n * Return the maximum amount of water a container can store.\n * \n * Notice that you may not slant the container.\n * \n * Example 1:\n * Input: height = [1,8,6,2,5,4,8,3,7]\n * Output: 49\n * Explanation: The above vertical lines are represented by array [1,8,6,2,5,4,8,3,7]. In this case, the max area of water (blue section) the container can contain is 49.\n * \n * Example 2:\n * Input: height = [1,1]\n * Output: 1\n * \n * Constraints:\n * - n == height.length\n * - 2 <= n <= 10^5\n * - 0 <= height[i] <= 10^4\n * \n * ---\n * ### Execution Flow Table (Example: height = [1,8,6,2])\n * \n * | Step | left | right | height[left] | height[right] | Area (h * w) | maxArea | Action |\n * | :--- | :--- | :---  | :---         | :---          | :---         | :---    | :--- |\n * | 0    | 0    | 3     | 1            | 2             | 1 * 3 = 3    | 3       | `height[left] < height[right]`, left++ |\n * | 1    | 1    | 3     | 8            | 2             | 2 * 2 = 4    | 4       | `height[left] > height[right]`, right-- |\n * | 2    | 1    | 2     | 8            | 6             | 6 * 1 = 6    | 6       | `height[left] > height[right]`, right-- |\n * | 3    | -    | -     | -            | -             | -            | 6       | `left == right`, Loop terminates |\n */\n\n/**\n * @param {number[]} height\n * @return {number}\n */\nvar maxArea = function (height) {\n    let left = 0;\n    let right = height.length - 1;\n    let maxArea = 0;\n\n    while (left < right) {\n        let h = Math.min(height[left], height[right]);\n        let w = right - left;\n        maxArea = Math.max(maxArea, h * w);\n\n        if (height[left] < height[right]) {\n            left++;\n        } else {\n            right--;\n        }\n    }\n\n    return maxArea;\n};\n",
      "language": "javascript"
    },
    {
      "id": "12",
      "title": "Integer to Roman",
      "difficulty": "Medium",
      "file": "Medium/0012_IntegerToRoman.js",
      "content": "/**\r\n * Problem #12: Integer to Roman (Medium)\r\n *\r\n * Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.\r\n *\r\n * Symbol       Value\r\n * I             1\r\n * V             5\r\n * X             10\r\n * L             50\r\n * C             100\r\n * D             500\r\n * M             1000\r\n *\r\n * For example, 2 is written as II in Roman numeral, just two one's added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.\r\n *\r\n * Roman numerals are usually written largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX. There are six instances where subtraction is used:\r\n *\r\n * I can be placed before V (5) and X (10) to make 4 and 9.\r\n * X can be placed before L (50) and C (100) to make 40 and 90.\r\n * C can be placed before D (500) and M (1000) to make 400 and 900.\r\n * Given an integer, convert it to a roman numeral.\r\n *\r\n * Example 1:\r\n * Input: num = 3\r\n * Output: \"III\"\r\n * Explanation: 3 is written as III in Roman numeral.\r\n *\r\n * Example 2:\r\n * Input: num = 4\r\n * Output: \"IV\"\r\n * Explanation: 4 is written as IV in Roman numeral.\r\n *\r\n * Example 3:\r\n * Input: num = 9\r\n * Output: \"IX\"\r\n * Explanation: 9 is written as IX in Roman numeral.\r\n *\r\n * Example 4:\r\n * Input: num = 58\r\n * Output: \"LVIII\"\r\n * Explanation: L = 50, V = 5, III = 3.\r\n *\r\n * Example 5:\r\n * Input: num = 1994\r\n * Output: \"MCMXCIV\"\r\n * Explanation: M = 1000, CM = 900, XC = 90 and IV = 4.\r\n *\r\n * Constraints:\r\n * - 1 <= num <= 3999\r\n */\r\n\r\n/**\r\n * @param {number} num\r\n * @return {string}\r\n */\r\nvar intToRoman = function (num) {\r\n  const values = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1];\r\n  const symbols = [\r\n    \"M\",\r\n    \"CM\",\r\n    \"D\",\r\n    \"CD\",\r\n    \"C\",\r\n    \"XC\",\r\n    \"L\",\r\n    \"XL\",\r\n    \"X\",\r\n    \"IX\",\r\n    \"V\",\r\n    \"IV\",\r\n    \"I\",\r\n  ];\r\n\r\n  let roman = \"\";\r\n\r\n  for (let i = 0; i < values.length; i++) {\r\n    while (num >= values[i]) {\r\n      roman += symbols[i];\r\n      num -= values[i];\r\n    }\r\n  }\r\n\r\n  return roman;\r\n};\r\n",
      "language": "javascript"
    },
    {
      "id": "15",
      "title": "3Sum",
      "difficulty": "Medium",
      "file": "Medium/0015_ThreeSum.js",
      "content": "/**\r\n * Problem #15: 3Sum (Medium)\r\n *\r\n * Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]]\r\n * such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.\r\n *\r\n * Notice that the solution set must not contain duplicate triplets.\r\n *\r\n * Example 1:\r\n * Input: nums = [-1,0,1,2,-1,-4]\r\n * Output: [[-1,-1,2],[-1,0,1]]\r\n *\r\n * Example 2:\r\n * Input: nums = []\r\n * Output: []\r\n *\r\n * Example 3:\r\n * Input: nums = [0]\r\n * Output: []\r\n *\r\n * Constraints:\r\n * 0 <= nums.length <= 3000\r\n * -10^5 <= nums[i] <= 10^5\r\n */\r\n\r\n/**\r\n * @param {number[]} nums\r\n * @return {number[][]}\r\n */\r\nvar threeSum = function (nums) {\r\n  let arr = nums.sort((a, b) => a - b);\r\n  let result = [];\r\n\r\n  for (let i = 0; i < arr.length; i++) {\r\n    if (i > 0 && arr[i] === arr[i - 1]) continue;\r\n\r\n    let left = i + 1;\r\n    let right = arr.length - 1;\r\n\r\n    while (left < right) {\r\n      let sum = arr[i] + arr[left] + arr[right];\r\n      if (sum == 0) {\r\n        result.push([arr[i], arr[left], arr[right]]);\r\n\r\n        while (left < right && arr[left] === arr[left + 1]) left++;\r\n        while (left < right && arr[right] === arr[right - 1]) right--;\r\n\r\n        left++;\r\n        right--;\r\n      } else if (sum < 0) {\r\n        left++;\r\n      } else {\r\n        right--;\r\n      }\r\n    }\r\n  }\r\n  return result;\r\n};\r\n",
      "language": "javascript"
    },
    {
      "id": "16",
      "title": "3Sum Closest",
      "difficulty": "Medium",
      "file": "Medium/0016_3SumClosest.js",
      "content": "/**\r\n * Problem #16: 3Sum Closest (Medium)\r\n *\r\n * Given an integer array nums of length n and an integer target, find three integers in nums such that the sum is closest to target.\r\n *\r\n * Return the sum of the three integers.\r\n *\r\n * You may assume that each input would have exactly one solution.\r\n *\r\n * Example 1:\r\n * Input: nums = [-1,2,1,-4], target = 1\r\n * Output: 2\r\n * Explanation: The sum that is closest to the target is 2. (-1 + 2 + 1 = 2).\r\n *\r\n * Example 2:\r\n * Input: nums = [0,0,0], target = 1\r\n * Output: 0\r\n *\r\n * Constraints:\r\n * 3 <= nums.length <= 1000\r\n * -1000 <= nums[i] <= 1000\r\n * -10^4 <= target <= 10^4\r\n */\r\n\r\n/**\r\n * @param {number[]} nums\r\n * @param {number} target\r\n * @return {number}\r\n */\r\nvar threeSumClosest = function (nums, target) {\r\n  nums.sort((a, b) => a - b);\r\n  let closest = nums[0] + nums[1] + nums[2];\r\n  for (let i = 0; i < nums.length - 2; i++) {\r\n    let left = i + 1;\r\n    let right = nums.length - 1;\r\n\r\n    while (left < right) {\r\n      let sum = nums[i] + nums[left] + nums[right];\r\n\r\n      if (Math.abs(sum - target) < Math.abs(closest - target)) {\r\n        closest = sum;\r\n      }\r\n\r\n      if (sum < target) {\r\n        left++;\r\n      } else if (sum > target) {\r\n        right--;\r\n      } else {\r\n        return sum;\r\n      }\r\n    }\r\n  }\r\n  return closest;\r\n};\r\n",
      "language": "javascript"
    },
    {
      "id": "17",
      "title": "Letter Combinations of a Phone Number",
      "difficulty": "Medium",
      "file": "Medium/0017_LetterCombinationsOfAPhoneNumber.js",
      "content": "/**\r\n * Problem #17: Letter Combinations of a Phone Number (Medium)\r\n *\r\n * Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order.\r\n *\r\n * A mapping of digits to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.\r\n *\r\n * Example 1:\r\n * Input: digits = \"23\"\r\n * Output: [\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]\r\n *\r\n * Example 2:\r\n * Input: digits = \"\"\r\n * Output: []\r\n *\r\n * Example 3:\r\n * Input: digits = \"2\"\r\n * Output: [\"a\",\"b\",\"c\"]\r\n *\r\n * Constraints:\r\n * 0 <= digits.length <= 4\r\n * digits[i] is a digit in the range ['2', '9'].\r\n */\r\n\r\n/**\r\n * @param {string} digits\r\n * @return {string[]}\r\n */\r\n\r\nconst keypad = {\r\n  1: \"\",\r\n  2: \"abc\",\r\n  3: \"def\",\r\n  4: \"ghi\",\r\n  5: \"jkl\",\r\n  6: \"mno\",\r\n  7: \"pqrs\",\r\n  8: \"tuv\",\r\n  9: \"wxyz\",\r\n};\r\nvar letterCombinations = function (digits) {\r\n  if (!digits.length) return [];\r\n\r\n  let result = [];\r\n\r\n  function backtrack(index, path) {\r\n    if (index === digits.length) {\r\n      result.push(path);\r\n      return;\r\n    }\r\n\r\n    let letters = keypad[digits[index]];\r\n\r\n    for (let char of letters) {\r\n      backtrack(index + 1, path + char);\r\n    }\r\n  }\r\n\r\n  backtrack(0, \"\");\r\n  return result;\r\n};\r\n",
      "language": "javascript"
    },
    {
      "id": "0019",
      "title": "Remove Nth Node From End Of List",
      "difficulty": "Medium",
      "file": "Medium/0019_RemoveNthNodeFromEndOfList.js",
      "content": "/**\r\n * Problem 19: Remove Nth Node From End of List\r\n * Difficulty: Medium\r\n *\r\n * Given the head of a linked list, remove the nth node from the end of the list and return its head.\r\n *\r\n * Example 1:\r\n * Input: head = [1,2,3,4,5], n = 2\r\n * Output: [1,2,3,5]\r\n *\r\n * Example 2:\r\n * Input: head = [1], n = 1\r\n * Output: []\r\n *\r\n * Example 3:\r\n * Input: head = [1,2], n = 1\r\n * Output: [1]\r\n *\r\n * Constraints:\r\n * - The number of nodes in the list is sz.\r\n * - 1 <= sz <= 30\r\n * - 0 <= Node.val <= 100\r\n * - 1 <= n <= sz\r\n *\r\n * Follow up: Could you do this in one pass?\r\n *\r\n * Execution Flow:\r\n * 1. Count the total length of the linked list\r\n * 2. Create a dummy node pointing to head\r\n * 3. Calculate position from start: length - n\r\n * 4. Traverse to the node before the target\r\n * 5. Skip the target node by updating next pointer\r\n * 6. Return dummy.next (new head)\r\n *\r\n * Time Complexity: O(L) where L is the length of the list (two passes)\r\n * Space Complexity: O(1) - only using constant extra space\r\n */\r\n\r\n/**\r\n * Definition for singly-linked list.\r\n * function ListNode(val, next) {\r\n *     this.val = (val===undefined ? 0 : val)\r\n *     this.next = (next===undefined ? null : next)\r\n * }\r\n */\r\n/**\r\n * @param {ListNode} head\r\n * @param {number} n\r\n * @return {ListNode}\r\n */\r\nvar removeNthFromEnd = function (head, n) {\r\n  let length = 0;\r\n  let curr = head;\r\n\r\n  // count length\r\n  while (curr) {\r\n    length++;\r\n    curr = curr.next;\r\n  }\r\n\r\n  let dummy = new ListNode(0, head);\r\n  curr = dummy;\r\n\r\n  // go to node before target\r\n  for (let i = 0; i < length - n; i++) {\r\n    curr = curr.next;\r\n  }\r\n\r\n  curr.next = curr.next.next;\r\n\r\n  return dummy.next;\r\n};\r\n\r\n/*\r\nFollow-up solution (One Pass - Two Pointers):\r\n\r\nvar removeNthFromEnd = function(head, n) {\r\n    let dummy = new ListNode(0, head);\r\n    let first = dummy;\r\n    let second = dummy;\r\n\r\n    // Advance first pointer by n+1 steps\r\n    for (let i = 0; i <= n; i++) {\r\n        first = first.next;\r\n    }\r\n\r\n    // Move both pointers until first reaches end\r\n    while (first) {\r\n        first = first.next;\r\n        second = second.next;\r\n    }\r\n\r\n    // Remove the nth node from end\r\n    second.next = second.next.next;\r\n\r\n    return dummy.next;\r\n};\r\n*/\r\n",
      "language": "javascript"
    },
    {
      "id": "0022",
      "title": "Generate Parentheses",
      "difficulty": "Medium",
      "file": "Medium/0022_GenerateParentheses.js",
      "content": "/**\r\n * Problem 22: Generate Parentheses\r\n * Difficulty: Medium\r\n *\r\n * Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.\r\n *\r\n * Example 1:\r\n * Input: n = 3\r\n * Output: [\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]\r\n *\r\n * Example 2:\r\n * Input: n = 1\r\n * Output: [\"()\"]\r\n *\r\n * Constraints:\r\n * - 1 <= n <= 8\r\n *\r\n * Strategy:\r\n * - Use backtracking (recursive DFS) to build parentheses strings.\r\n * - Keep track of open and close counts.\r\n * - Add '(' when open < n.\r\n * - Add ')' when close < open.\r\n * - Accept string when length reaches 2*n.\r\n *\r\n * Time Complexity: O(Catalan(n)) in terms of number of valid combinations.\r\n * Space Complexity: O(n) recursion stack + result size.\r\n */\r\n\r\n/**\r\n * @param {number} n\r\n * @return {string[]}\r\n */\r\nvar generateParenthesis = function (n) {\r\n  const result = [];\r\n\r\n  function backtrack(path, open, close) {\r\n    if (path.length === 2 * n) {\r\n      result.push(path);\r\n      return;\r\n    }\r\n\r\n    if (open < n) {\r\n      backtrack(path + \"(\", open + 1, close);\r\n    }\r\n\r\n    if (close < open) {\r\n      backtrack(path + \")\", open, close + 1);\r\n    }\r\n  }\r\n\r\n  backtrack(\"\", 0, 0);\r\n  return result;\r\n};\r\n",
      "language": "javascript"
    },
    {
      "id": "0029",
      "title": "Divide Two Integers",
      "difficulty": "Medium",
      "file": "Medium/0029_DivideTwoIntegers.js",
      "content": "/**\r\n * Problem 29: Divide Two Integers\r\n * Difficulty: Medium\r\n *\r\n * Given two integers dividend and divisor, divide two integers without using multiplication, division, and mod operator.\r\n * The integer division should truncate toward zero, which means losing its fractional part.\r\n * You may assume we are dealing with an environment that could only store integers within the 32-bit signed integer range: [−2^31, 2^31 − 1].\r\n * For this problem, if the quotient is strictly greater than 2^31 − 1, then return 2^31 − 1, and if the quotient is strictly less than −2^31, then return −2^31.\r\n *\r\n * Example 1:\r\n * Input: dividend = 10, divisor = 3\r\n * Output: 3\r\n *\r\n * Example 2:\r\n * Input: dividend = 7, divisor = -3\r\n * Output: -2\r\n *\r\n * Constraints:\r\n * - -2^31 <= dividend, divisor <= 2^31 - 1\r\n * - divisor != 0\r\n *\r\n * Time Complexity: O(log n) where n is the dividend\r\n * Space Complexity: O(1)\r\n */\r\n\r\n/**\r\n * @param {number} dividend\r\n * @param {number} divisor\r\n * @return {number}\r\n */\r\nvar divide = function(dividend, divisor) {\r\n    const INT_MAX = 2147483647;\r\n    const INT_MIN = -2147483648;\r\n\r\n    // Handle overflow\r\n    if (dividend === INT_MIN && divisor === -1) {\r\n        return INT_MAX;\r\n    }\r\n    if (dividend === INT_MIN && divisor === 1) {\r\n        return INT_MIN;\r\n    }\r\n\r\n    // Work with negatives only\r\n    let negatives = 2;\r\n    if (dividend > 0) {\r\n        dividend = -dividend;\r\n        negatives--;\r\n    }\r\n    if (divisor > 0) {\r\n        divisor = -divisor;\r\n        negatives--;\r\n    }\r\n\r\n    let result = 0;\r\n\r\n    while (dividend <= divisor) {\r\n        let temp = divisor;\r\n        let multiple = 1;\r\n\r\n        // Prevent overflow when doubling\r\n        while (temp >= (INT_MIN >> 1) && dividend <= (temp << 1)) {\r\n            temp <<= 1;\r\n            multiple <<= 1;\r\n        }\r\n\r\n        dividend -= temp;\r\n        result += multiple;\r\n    }\r\n\r\n    // Apply sign\r\n    return negatives === 1 ? -result : result;\r\n};",
      "language": "javascript"
    }
  ],
  "Hard": []
};
const JOURNAL_DATA = [
  {
    "title": "Day 8: April 4, 2026",
    "content": "**Problems Solved:** 1 ([#29](file:///e:/LeetCode/Medium/0029_DivideTwoIntegers.js))\n\n**Experience & Learning:**\n- **Bit Manipulation Division**: Solved \"Divide Two Integers\" using bit shifting for efficient division without multiplication/division operators. The key is doubling divisor and multiple until overflow risk, then subtracting.\n- **Overflow Handling**: Learned to work with negatives to avoid overflow issues, and handle edge cases like INT_MIN/-1.\n- **Bit Shifting Mastery**: Reinforced bit operations for performance optimization in constrained environments.\n- **Milestone**: Reached **37 total problems solved**! Strong April momentum.\n\n*\"Building the future of enterprise software, one line of code at a time.\"*"
  },
  {
    "title": "Day 7: April 3, 2026",
    "content": "**Problems Solved:** 2 ([#108](file:///e:/LeetCode/Easy/0108_ConvertSortedArrayToBinarySearchTree.js), [#121](file:///e:/LeetCode/Easy/0121_BestTimeToBuyAndSellStock.js))\n\n**Experience & Learning:**\n- **Balanced BST from Sorted Array**: Solved \"Convert Sorted Array to Binary Search Tree\" with mid-point recursion. This ensures balanced tree height by using middle element as current root.\n- **Divide and Conquer**: Break the array into left and right halves repeatedly, building subtree recursively. Helps guarantee O(n) build time.\n- **Stock Trade Insight**: Solved \"Best Time to Buy and Sell Stock\" by tracking minimum price and max difference (profit). This highlights single-scan greedy decision-making.\n- **Recursive Confidence + Greedy (O(n))**: Reinforced both recursion for trees and in-place greedy for array profit.\n- **Milestone**: Reached **36 total problems solved**! Daily momentum continues.\n\n*\"Building the future of enterprise software, one line of code at a time.\"*\n\n---"
  },
  {
    "title": "Day 6: April 2, 2026",
    "content": "**Problems Solved:** 2 ([#19](file:///e:/LeetCode/Medium/0019_RemoveNthNodeFromEndOfList.js), [#22](file:///e:/LeetCode/Medium/0022_GenerateParentheses.js))\n\n**Experience & Learning:**\n- **Linked List Manipulation**: Solved \"Remove Nth Node From End of List\" using a two-pass approach. First pass counts the length, second pass finds and removes the target node. The key insight was using a dummy node to handle edge cases where the head needs to be removed.\n- **Dummy Node Pattern**: Learned the importance of dummy nodes for linked list problems. They simplify boundary conditions and make the code more robust.\n- **Backtracking**: Solved \"Generate Parentheses\" using recursive backtracking. Key rules: add \"(\" until open count reaches n; add \")\" when close < open. Stop when length hits 2*n.\n- **Follow-up Challenge**: The linked list problem includes a one-pass solution using two pointers - fast pointer moves n+1 steps ahead, then both move together until fast reaches end. This is more efficient but requires careful pointer management.\n- **Milestone**: Reached **34 total problems solved**! Building momentum with consistent daily practice.\n\n*\"Building the future of enterprise software, one line of code at a time.\"*\n\n---"
  },
  {
    "title": "Day 5: April 1, 2026",
    "content": "**Problems Solved:** 5 ([#12](file:///e:/LeetCode/Medium/0012_IntegerToRoman.js), [#15](file:///e:/LeetCode/Medium/0015_ThreeSum.js), [#16](file:///e:/LeetCode/Medium/0016_3SumClosest.js), [#17](file:///e:/LeetCode/Medium/0017_LetterCombinationsOfAPhoneNumber.js), [#104](file:///e:/LeetCode/Easy/0104_MaximumDepthOfBinaryTree.js))\n\n**Experience & Learning:**\n- **Greedy Algorithm**: Solved \"Integer to Roman\" using a greedy approach with predefined value-symbol pairs. Starting from the largest values (1000, 900, 500, etc.) and subtracting them from the input number while building the Roman numeral string. This ensures we always use the largest possible Roman numeral symbols first, which is the optimal greedy strategy for this problem.\n- **Two Pointers + Sorting**: Solved \"3Sum\" with a sorted array and two-pointer technique, handling duplicates with fast skip conditions to avoid repeat triplets in the result.\n- **Two Pointers + Target Tracking**: Solved \"3Sum Closest\" using a similar two-pointer approach but tracking the closest sum to target instead of exact matches. The key insight is maintaining the minimum absolute difference while iterating through possible combinations.\n- **Backtracking**: Solved \"Letter Combinations of a Phone Number\" using backtracking to generate all possible combinations. The recursive approach explores each digit's possible letters, building combinations by adding one character at a time until all digits are processed.\n- **Tree Recursion**: Solved \"Maximum Depth of Binary Tree\" using recursive depth-first search, calculating the maximum depth by taking the max of left and right subtrees plus one. This is a classic tree traversal pattern that demonstrates the power of recursion for hierarchical data structures.\n- **Milestone**: Reached **32 total problems solved**! Continuing the momentum with a mix of Easy and Medium challenges.\n\n*\"Building the future of enterprise software, one line of code at a time.\"*\n\n---"
  },
  {
    "title": "Day 4: March 30, 2026",
    "content": "**Problems Solved:** 3 ([#6](file:///e:/LeetCode/Medium/0006_ZigzagConversion.js), [#7](file:///e:/LeetCode/Medium/0007_ReverseInteger.js), [#8](file:///e:/LeetCode/Medium/0008_StringToIntegerAtoi.js))\n\n**Experience & Learning:**\n- **String & Array Manipulation**: Tackled \"Zigzag Conversion,\" manipulating rows and arrays using a bidirectional pointer (`direction`). It was a clever way to simulate downward and upward diagonal reads without complex 2D matrices.\n- **Integer Manipulation**: Solved two classic medium problems: \"Reverse Integer\" and \"String to Integer (atoi)\". Both of these required careful consideration of 32-bit signed integer boundaries (`-2147483648` to `2147483647`).\n- **Edge Cases**: In `atoi`, I learned that string parsing problems are 90% edge-cases. Dealing with leading whitespaces, negative/positive signs, correctly stopping at non-digit characters, and bounding the final result really reinforced the importance of step-by-step state tracking.\n- **Milestone**: Reached **26 total problems solved**! Finding a steady rhythm with Medium-difficulty challenges.\n\n*\"Building the future of enterprise software, one line of code at a time.\"*\n\n---"
  },
  {
    "title": "Day 3: March 29, 2026",
    "content": "**Problems Solved:** 7 ([#70](file:///e:/LeetCode/Easy/0070_ClimbingStairs.js), [#94](file:///e:/LeetCode/Easy/0094_BinaryTreeInorderTraversal.js), [#100](file:///e:/LeetCode/Easy/0100_SameTree.js), [#101](file:///e:/LeetCode/Easy/0101_SymmetricTree.js), [#2](file:///e:/LeetCode/Medium/0002_AddTwoNumbers.js), [#3](file:///e:/LeetCode/Medium/0003_LongestSubstringWithoutRepeatingCharacters.js), [#5](file:///e:/LeetCode/Medium/0005_LongestPalindromicSubstring.js))\n\n**Experience & Learning:**\n- **Dynamic Programming (DP)**: Solved \"Climbing Stairs,\" which is a classic introduction to DP. It was interesting to see how the problem breaks down into smaller sub-problems. It's essentially the Fibonacci sequence where each step is the sum of the ways to reach the two previous steps. \n- **Tree Structures**: Added \"Binary Tree Inorder Traversal,\" \"Same Tree,\" and \"Symmetric Tree.\" These problems highlighted the power of **Recursion** for traversing and comparing hierarchical structures. The \"mirror image\" logic for symmetry was a direct extension of the \"same tree\" comparison.\n- **Sliding Window**: Mastered the **Sliding Window** technique with \"Longest Substring Without Repeating Characters.\" Using a `Set` to track the current unique sequence and shrinking the window from the left is an elegant solution to an $O(n)$ problem.\n- **Expand Around Center**: Solved \"Longest Palindromic Substring\" by expanding from each character (odd length) and each gap between characters (even length). This is an intuitive $O(n^2)$ solution that reinforces symmetry concepts from the earlier tree problems. \n- **Milestone 23**: Reached a total of **23 problems solved**. Today has been incredibly productive with a strong mix of Easy and Medium problems, plus a major repository cleanup!\n\n---"
  },
  {
    "title": "Day 2: March 27, 2026",
    "content": "**Problems Solved:** 10 ([#26](file:///e:/LeetCode/Easy/0026_RemoveDuplicatesFromSortedArray.js), [#27](file:///e:/LeetCode/Easy/0027_RemoveElement.js), [#28](file:///e:/LeetCode/Easy/0028_FindIndexFirstOccurrence.js), [#35](file:///e:/LeetCode/Easy/0035_SearchInsertPosition.js), [#58](file:///e:/LeetCode/Easy/0058_LengthOfLastWord.js), [#66](file:///e:/LeetCode/Easy/0066_PlusOne.js), [#67](file:///e:/LeetCode/Easy/0067_AddBinary.js), [#69](file:///e:/LeetCode/Easy/0069_SqrtX.js), [#83](file:///e:/LeetCode/Easy/0083_RemoveDuplicatesFromSortedList.js), [#88](file:///e:/LeetCode/Easy/0088_MergeSortedArray.js))\n\n**Experience & Learning:**\n...\n- **In-Place Merging**: Mastered the technique of merging two sorted arrays in-place by iterating backwards. This prevents overwriting data in the first array and is highly efficient (O(1) space).\n- **Consistency**: Reached **16 total problems solved**! Today has been legendary with 10 new solutions documented in a single day.\n\n---"
  },
  {
    "title": "Day 1: March 26, 2026",
    "content": "**Problems Solved:** 6 ([#1](file:///e:/LeetCode/Easy/0001_TwoSum.js), [#9](file:///e:/LeetCode/Easy/0009_PalindromeNumber.js), [#13](file:///e:/LeetCode/Easy/0013_RomanToInteger.js), [#14](file:///e:/LeetCode/Easy/0014_LongestCommonPrefix.js), [#20](file:///e:/LeetCode/Easy/0020_ValidParentheses.js), [#21](file:///e:/LeetCode/Easy/0021_MergeTwoSortedLists.js))\n\n**Experience & Learning:**\n- **Project Structure**: Set up the foundational structure for this repository, organizing problems by difficulty and implementing an automated progress tracking system via `README.md` files.\n- **Core Algorithms**: Tackled fundamental problems involving hash maps (Two Sum), string manipulation (Longest Common Prefix, Valid Parentheses), and math (Roman to Integer, Palindrome Number).\n- **Portfolio Integration**: Linked this repository to my main GitHub portfolio and added dynamic stats cards to showcase my progress.\n- **Git Workflow**: Established a clean workflow for committing and pushing solutions with appropriate documentation."
  }
];