/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file contains all your LeetCode solution data for the interactive dashboard.
 */
const SOLUTIONS = {
  "Easy": [
    {
      "id": "0001",
      "title": "Two Sum",
      "difficulty": "Easy",
      "file": "Easy/0001_TwoSum.js",
      "content": "/**\n * Problem #1: Two Sum\n * \n * Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.\n * You may assume that each input would have exactly one solution, and you may not use the same element twice.\n * You can return the answer in any order.\n * \n * Example 1:\n * Input: nums = [2,7,11,15], target = 9\n * Output: [0,1]\n * Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].\n * \n * Example 2:\n * Input: nums = [3,2,4], target = 6\n * Output: [1,2]\n * \n * Example 3:\n * Input: nums = [3,3], target = 6\n * Output: [0,1]\n */\n\n/**\n * @param {number[]} nums\n * @param {number} target\n * @return {number[]}\n */\nvar twoSum = function(nums, target) {\n    var ans = [];\n    for(i=0;i<nums.length;i++){\n        for(j=i+1;j<nums.length;j++){\n            if(nums[i]+nums[j] == target){\n                ans.push(i,j);\n                break;\n            }\n        }\n    }\n    return ans;\n};\n"
    },
    {
      "id": "0009",
      "title": "Palindrome Number",
      "difficulty": "Easy",
      "file": "Easy/0009_PalindromeNumber.js",
      "content": "/**\n * Problem #9: Palindrome Number\n * \n * Given an integer x, return true if x is a palindrome, and false otherwise.\n * \n * Example 1:\n * Input: x = 121\n * Output: true\n * Explanation: 121 reads as 121 from left to right and from right to left.\n * \n * Example 2:\n * Input: x = -121\n * Output: false\n * Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.\n * \n * Example 3:\n * Input: x = 10\n * Output: false\n * Explanation: Reads 01 from right to left. Therefore it is not a palindrome.\n */\n\n/**\n * @param {number} x\n * @return {boolean}\n */\nvar isPalindrome = function(x) {\n    if(x.toString() == x.toString().split('').reverse().join(''))\n        return true;\n    else \n        return false;\n};\n"
    },
    {
      "id": "0013",
      "title": "Roman To Integer",
      "difficulty": "Easy",
      "file": "Easy/0013_RomanToInteger.js",
      "content": "/**\n * Problem #13: Roman to Integer\n * \n * Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.\n * Symbol       Value\n * I             1\n * V             5\n * X             10\n * L             50\n * C             100\n * D             500\n * M             1000\n * \n * For example, 2 is written as II in Roman numeral, just two ones added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.\n * \n * Roman numerals are usually written largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX. There are six instances where subtraction is used:\n * - I can be placed before V (5) and X (10) to make 4 and 9. \n * - X can be placed before L (50) and C (100) to make 40 and 90. \n * - C can be placed before D (500) and M (1000) to make 400 and 900.\n * \n * Example 1:\n * Input: s = \"III\"\n * Output: 3\n * \n * Example 2:\n * Input: s = \"LVIII\"\n * Output: 58\n * Explanation: L = 50, V = 5, III = 3.\n * \n * Example 3:\n * Input: s = \"MCMXCIV\"\n * Output: 1994\n * Explanation: M = 1000, CM = 900, XC = 90 and IV = 4.\n */\n\nconst romanMap = {\n  'I': 1,\n  'V': 5,\n  'X': 10,\n  'L': 50,\n  'C': 100,\n  'D': 500,\n  'M': 1000\n};\n\n/**\n * @param {string} s\n * @return {number}\n */\nvar romanToInt = function(s) {\n  let total = 0;\n\n  for (let i = 0; i < s.length; i++) {\n    // Check if current value < next value (subtraction case)\n    if (i + 1 < s.length && romanMap[s[i]] < romanMap[s[i + 1]]) {\n      total += romanMap[s[i + 1]] - romanMap[s[i]];\n      i++; // skip the next character since we used it\n    } else {\n      total += romanMap[s[i]];\n    }\n  }\n\n  return total;\n};\n"
    },
    {
      "id": "0014",
      "title": "Longest Common Prefix",
      "difficulty": "Easy",
      "file": "Easy/0014_LongestCommonPrefix.js",
      "content": "/**\n * Problem #14: Longest Common Prefix\n * \n * Write a function to find the longest common prefix string amongst an array of strings.\n * If there is no common prefix, return an empty string \"\".\n * \n * Example 1:\n * Input: strs = [\"flower\",\"flow\",\"flight\"]\n * Output: \"fl\"\n * \n * Example 2:\n * Input: strs = [\"dog\",\"racecar\",\"car\"]\n * Output: \"\"\n * Explanation: There is no common prefix among the input strings.\n */\n\n/**\n * @param {string[]} strs\n * @return {string}\n */\nvar longestCommonPrefix = function (strs) {\n    if (strs.length == 0) return ``;\n\n    let prefix = strs[0];\n    for (i = 0; i < strs.length; i++) {\n        while (strs[i].indexOf(prefix) !== 0) {\n            prefix = prefix.slice(0, -1);\n            if (prefix === \"\") return \"\";\n        }\n    }\n    return prefix;\n};\n"
    },
    {
      "id": "0020",
      "title": "Valid Parentheses",
      "difficulty": "Easy",
      "file": "Easy/0020_ValidParentheses.js",
      "content": "/**\n * Problem #20: Valid Parentheses\n * \n * Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.\n * \n * An input string is valid if:\n * 1. Open brackets must be closed by the same type of brackets.\n * 2. Open brackets must be closed in the correct order.\n * 3. Every closing bracket must have a corresponding open bracket of the same type.\n * \n * Example 1:\n * Input: s = \"()\"\n * Output: true\n * \n * Example 2:\n * Input: s = \"()[]{}\"\n * Output: true\n * \n * Example 3:\n * Input: s = \"(]\"\n * Output: false\n */\n\n/**\n * @param {string} s\n * @return {boolean}\n */\nvar isValid = function (s) {\n    if (s.length == 0) return false;\n\n    const stack = [];\n    const map = {\n        ')': '(',\n        '}': '{',\n        ']': '['\n    };\n    \n    for (let char of s) {\n        if (char === '(' || char === '{' || char === '[') {\n            stack.push(char);\n        } else {\n            if (stack.length === 0 || stack.pop() !== map[char]) {\n                return false;\n            }\n        }\n    }\n\n    return stack.length === 0;\n};\n"
    },
    {
      "id": "0021",
      "title": "Merge Two Sorted Lists",
      "difficulty": "Easy",
      "file": "Easy/0021_MergeTwoSortedLists.js",
      "content": "/**\n * Problem #21: Merge Two Sorted Lists\n * \n * You are given the heads of two sorted linked lists list1 and list2.\n * Merge the two lists in a one sorted list. The list should be made by splicing together the nodes of the first two lists.\n * Return the head of the merged linked list.\n * \n * Example 1:\n * Input: list1 = [1,2,4], list2 = [1,3,4]\n * Output: [1,1,2,3,4,4]\n * \n * Example 2:\n * Input: list1 = [], list2 = []\n * Output: []\n * \n * Example 3:\n * Input: list1 = [], list2 = [0]\n * Output: [0]\n */\n\n/**\n * Definition for singly-linked list.\n * function ListNode(val, next) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.next = (next===undefined ? null : next)\n * }\n */\n/**\n * @param {ListNode} list1\n * @param {ListNode} list2\n * @return {ListNode}\n */\nvar mergeTwoLists = function(list1, list2) {\n    let dummy = new ListNode(-1);\n    let current = dummy;\n\n    while (list1 !== null && list2 !== null) {\n        if (list1.val <= list2.val) {\n            current.next = list1;\n            list1 = list1.next;\n        } else {\n            current.next = list2;\n            list2 = list2.next;\n        }\n        current = current.next;\n    }\n    current.next = list1 !== null ? list1 : list2;\n\n    return dummy.next;\n};\n"
    },
    {
      "id": "0026",
      "title": "Remove Duplicates From Sorted Array",
      "difficulty": "Easy",
      "file": "Easy/0026_RemoveDuplicatesFromSortedArray.js",
      "content": "/**\n * Problem #26: Remove Duplicates from Sorted Array\n * \n * Given an integer array nums sorted in non-decreasing order, remove the duplicates in-place such that each unique element appears only once.\n * The relative order of the elements should be kept the same. Then return the number of unique elements in nums.\n * \n * Consider the number of unique elements of nums to be k, to get accepted, you need to do the following things:\n * 1. Modify the array nums such that the first k elements of nums contain the unique elements in the order they were initially in nums.\n * 2. Return k.\n * \n * Example 1:\n * Input: nums = [1,1,2]\n * Output: 2, nums = [1,2,_]\n * \n * Example 2:\n * Input: nums = [0,0,1,1,1,2,2,3,3,4]\n * Output: 5, nums = [0,1,2,3,4,_,_,_,_,_]\n */\n\n/**\n * @param {number[]} nums\n * @return {number}\n */\nvar removeDuplicates = function (nums) {\n    if (nums.length == 0) return 0;\n\n    var k = 0;\n\n    for (var i = 0; i < nums.length; i++) {\n        if (nums[k] != nums[i]) {\n            k++;\n            nums[k] = nums[i];\n        }\n    }\n    return k + 1;\n};\n"
    },
    {
      "id": "0027",
      "title": "Remove Element",
      "difficulty": "Easy",
      "file": "Easy/0027_RemoveElement.js",
      "content": "/**\n * Problem #27: Remove Element\n * \n * Given an integer array nums and an integer val, remove all occurrences of val in nums in-place.\n * The order of the elements may be changed. Then return the number of elements in nums which are not equal to val.\n * \n * Consider the number of elements in nums which are not equal to val be k, to get accepted, you need to do the following things:\n * 1. Modify the array nums such that the first k elements of nums contain the elements which are not equal to val.\n * 2. Return k.\n * \n * Example 1:\n * Input: nums = [3,2,2,3], val = 3\n * Output: 2, nums = [2,2,_,_]\n * \n * Example 2:\n * Input: nums = [0,1,2,2,3,0,4,2], val = 2\n * Output: 5, nums = [0,1,4,0,3,_,_,_]\n */\n\n/**\n * @param {number[]} nums\n * @param {number} val\n * @return {number}\n */\nvar removeElement = function (nums, val) {\n    if (nums.length == 0) return 0;\n\n    var k = 0;\n    for (var i = 0; i < nums.length; i++) {\n        if (nums[i] !== val) {\n            nums[k] = nums[i]\n            k++;\n        }\n    }\n    return k;\n};\n"
    },
    {
      "id": "0028",
      "title": "Find Index First Occurrence",
      "difficulty": "Easy",
      "file": "Easy/0028_FindIndexFirstOccurrence.js",
      "content": "/**\n * Problem #28: Find the Index of the First Occurrence in a String\n * \n * Given two strings needle and haystack, return the index of the first occurrence of needle in haystack, or -1 if needle is not part of haystack.\n * \n * Example 1:\n * Input: haystack = \"sadbutsad\", needle = \"sad\"\n * Output: 0\n * Explanation: \"sad\" occurs at index 0 and 6. The first occurrence is at index 0.\n * \n * Example 2:\n * Input: haystack = \"leetcode\", needle = \"leeto\"\n * Output: -1\n * Explanation: \"leeto\" did not occur in \"leetcode\", so we return -1.\n */\n\n/**\n * @param {string} haystack\n * @param {string} needle\n * @return {number}\n */\nvar strStr = function(haystack, needle) {\n    if (needle === \"\") return 0;\n    \n    for (let i = 0; i <= haystack.length - needle.length; i++) {\n        if (haystack[i] == needle[0]) {\n            if (haystack.slice(i, i + needle.length) == needle) {\n                return i;\n            }\n        }\n    }\n    return -1;\n};\n"
    },
    {
      "id": "0035",
      "title": "Search Insert Position",
      "difficulty": "Easy",
      "file": "Easy/0035_SearchInsertPosition.js",
      "content": "/**\n * Problem #35: Search Insert Position\n * \n * Given a sorted array of distinct integers and a target value, return the index if the target is found.\n * If not, return the index where it would be if it were inserted in order.\n * You must write an algorithm with O(log n) runtime complexity.\n * \n * Example 1:\n * Input: nums = [1,3,5,6], target = 5\n * Output: 2\n * \n * Example 2:\n * Input: nums = [1,3,5,6], target = 2\n * Output: 1\n * \n * Example 3:\n * Input: nums = [1,3,5,6], target = 7\n * Output: 4\n */\n\n/**\n * @param {number[]} nums\n * @param {number} target\n * @return {number}\n */\nvar searchInsert = function(nums, target) {\n    if (nums.length == 0) return 0;\n    \n    for (let i = 0; i < nums.length; i++) {\n        if (nums[i] >= target) {\n            return i;\n        }\n    }\n    return nums.length;\n};\n"
    },
    {
      "id": "0058",
      "title": "Length Of Last Word",
      "difficulty": "Easy",
      "file": "Easy/0058_LengthOfLastWord.js",
      "content": "/**\n * Problem #58: Length of Last Word\n * \n * Given a string s consisting of words and spaces, return the length of the last word in the string.\n * A word is a maximal substring consisting of non-space characters only.\n * \n * Example 1:\n * Input: s = \"Hello World\"\n * Output: 5\n * Explanation: The last word is \"World\" with length 5.\n * \n * Example 2:\n * Input: s = \"   fly me   to   the moon  \"\n * Output: 4\n * Explanation: The last word is \"moon\" with length 4.\n * \n * Example 3:\n * Input: s = \"luffy is still joyboy\"\n * Output: 6\n * Explanation: The last word is \"joyboy\" with length 6.\n */\n\n/**\n * @param {string} s\n * @return {number}\n */\nvar lengthOfLastWord = function (s) {\n    let length = 0;\n    let i = s.length - 1;\n\n    // Skip trailing spaces\n    while (i >= 0 && s[i] === \" \") {\n        i--;\n    }\n\n    // Count characters of the last word\n    while (i >= 0 && s[i] !== \" \") {\n        length++;\n        i--;\n    }\n\n    return length;\n};\n"
    },
    {
      "id": "0066",
      "title": "Plus One",
      "difficulty": "Easy",
      "file": "Easy/0066_PlusOne.js",
      "content": "/**\n * Problem #66: Plus One\n * \n * You are given a large integer represented as an integer array digits, where each digits[i] is the ith digit of the integer. \n * The digits are ordered from most significant to least significant in left-to-right order. \n * The large integer does not contain any leading 0's, except for the number 0 itself.\n * \n * Increment the large integer by one and return the resulting array of digits.\n * \n * Example 1:\n * Input: digits = [1,2,3]\n * Output: [1,2,4]\n * Explanation: The array represents the integer 123. Incrementing by one gives 123 + 1 = 124. Thus, the result should be [1,2,4].\n * \n * Example 2:\n * Input: digits = [4,3,2,1]\n * Output: [4,3,2,2]\n * Explanation: The array represents the integer 4321. Incrementing by one gives 4321 + 1 = 4322. Thus, the result should be [4,3,2,2].\n * \n * Example 3:\n * Input: digits = [9]\n * Output: [1,0]\n * Explanation: The array represents the integer 9. Incrementing by one gives 9 + 1 = 10. Thus, the result should be [1,0].\n */\n\n/**\n * @param {number[]} digits\n * @return {number[]}\n */\nvar plusOne = function(digits) {\n    for (let i = digits.length - 1; i >= 0; i--) {\n        if (digits[i] < 9) {\n            digits[i]++;\n            return digits;\n        }\n        digits[i] = 0;\n    }\n\n    // If we're here, it means all digits were 9 (e.g., [9,9,9] -> [0,0,0])\n    digits.unshift(1);\n    return digits;\n};\n"
    },
    {
      "id": "0067",
      "title": "Add Binary",
      "difficulty": "Easy",
      "file": "Easy/0067_AddBinary.js",
      "content": "/**\n * Problem #67: Add Binary\n * \n * Given two binary strings a and b, return their sum as a binary string.\n * \n * Example 1:\n * Input: a = \"11\", b = \"1\"\n * Output: \"100\"\n * \n * Example 2:\n * Input: a = \"1010\", b = \"1011\"\n * Output: \"10101\"\n */\n\n/**\n * @param {string} a\n * @param {string} b\n * @return {string}\n */\nvar addBinary = function (a, b) {\n    let i = a.length - 1;\n    let j = b.length - 1;\n    let carry = 0;\n    let result = \"\";\n\n    while (i >= 0 || j >= 0 || carry) {\n        let sum = carry;\n\n        if (i >= 0) sum += +a[i--];\n        if (j >= 0) sum += +b[j--];\n\n        result = (sum % 2) + result; // add bit\n        carry = Math.floor(sum / 2); // carry\n    }\n    return result;\n};\n"
    },
    {
      "id": "0069",
      "title": "Sqrt X",
      "difficulty": "Easy",
      "file": "Easy/0069_SqrtX.js",
      "content": "/**\n * Problem #69: Sqrt(x)\n * \n * Given a non-negative integer x, return the square root of x rounded down to the nearest integer. \n * The returned integer should be non-negative as well.\n * You must not use any built-in exponent function or operator.\n * \n * Example 1:\n * Input: x = 4\n * Output: 2\n * Explanation: The square root of 4 is 2, so we return 2.\n * \n * Example 2:\n * Input: x = 8\n * Output: 2\n * Explanation: The square root of 8 is 2.82842..., and since we round it down to the nearest integer, 2 is returned.\n */\n\n/**\n * @param {number} x\n * @return {number}\n */\nvar mySqrt = function(x) {\n    if (x < 2) return x;\n\n    let right = x;\n    let left = 1;\n    let ans = 0;\n\n    while (left <= right) {\n        let mid = Math.floor((left + right) / 2);\n        let temp = mid * mid;\n        if (temp == x) {\n            return mid;\n        } else if (temp < x) {\n            ans = mid;\n            left = mid + 1;\n        } else {\n            right = mid - 1;\n        }\n    }\n    return ans;\n};\n"
    },
    {
      "id": "0070",
      "title": "Climbing Stairs",
      "difficulty": "Easy",
      "file": "Easy/0070_ClimbingStairs.js",
      "content": "/**\n * Problem #70: Climbing Stairs\n * \n * You are climbing a staircase. It takes n steps to reach the top.\n * Each time you can either climb 1 or 2 steps. \n * In how many distinct ways can you climb to the top?\n * \n * Example 1:\n * Input: n = 2\n * Output: 2\n * Explanation: There are two ways to climb to the top.\n * 1. 1 step + 1 step\n * 2. 2 steps\n * \n * Example 2:\n * Input: n = 3\n * Output: 3\n * Explanation: There are three ways to climb to the top.\n * 1. 1 step + 1 step + 1 step\n * 2. 1 step + 2 steps\n * 3. 2 steps + 1 step\n * \n * Constraints:\n * 1 <= n <= 45\n */\n\n/**\n * @param {number} n\n * @return {number}\n */\nvar climbStairs = function (n) {\n    // Base cases\n    if (n < 3) return n;\n\n    // We only need the last two values (Fibonacci approach)\n    let p1 = 2; // ways to reach the previous step (n-1)\n    let p2 = 1; // ways to reach the step before that (n-2)\n    \n    for (let i = 3; i <= n; i++) {\n        let current = p1 + p2;\n        p2 = p1;\n        p1 = current;\n    }\n\n    return p1;\n};\n"
    },
    {
      "id": "0083",
      "title": "Remove Duplicates From Sorted List",
      "difficulty": "Easy",
      "file": "Easy/0083_RemoveDuplicatesFromSortedList.js",
      "content": "/**\n * Problem #83: Remove Duplicates from Sorted List\n * \n * Given the head of a sorted linked list, delete all duplicates such that each element appears only once. \n * Return the linked list sorted as well.\n * \n * Example 1:\n * Input: head = [1,1,2]\n * Output: [1,2]\n * \n * Example 2:\n * Input: head = [1,1,2,3,3]\n * Output: [1,2,3]\n * \n * Constraints:\n * - The number of nodes in the list is in the range [0, 300].\n * - -100 <= Node.val <= 100\n * - The list is guaranteed to be sorted in ascending order.\n */\n\n/**\n * Definition for singly-linked list.\n * function ListNode(val, next) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.next = (next===undefined ? null : next)\n * }\n */\n\n/**\n * @param {ListNode} head\n * @return {ListNode}\n */\nvar deleteDuplicates = function(head) {\n    let current = head;\n\n    while (current && current.next) {\n        if (current.val === current.next.val) {\n            // Found a duplicate, skip the next node\n            current.next = current.next.next; \n        } else {\n            // Move to the next unique node\n            current = current.next; \n        }\n    }\n\n    return head;\n};\n"
    },
    {
      "id": "0088",
      "title": "Merge Sorted Array",
      "difficulty": "Easy",
      "file": "Easy/0088_MergeSortedArray.js",
      "content": "/**\n * Problem #88: Merge Sorted Array\n * \n * You are given two integer arrays nums1 and nums2, sorted in non-decreasing order, \n * and two integers m and n, representing the number of elements in nums1 and nums2 respectively.\n * \n * Merge nums1 and nums2 into a single array sorted in non-decreasing order.\n * \n * The final sorted array should not be returned by the function, but instead be stored inside the array nums1. \n * To accommodate this, nums1 has a length of m + n, where the first m elements denote the elements that \n * should be merged, and the last n elements are set to 0 and should be ignored. nums2 has a length of n.\n * \n * Example 1:\n * Input: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3\n * Output: [1,2,2,3,5,6]\n * \n * Example 2:\n * Input: nums1 = [1], m = 1, nums2 = [], n = 0\n * Output: [1]\n * \n * Example 3:\n * Input: nums1 = [0], m = 0, nums2 = [1], n = 1\n * Output: [1]\n */\n\n/**\n * @param {number[]} nums1\n * @param {number} m\n * @param {number[]} nums2\n * @param {number} n\n * @return {void} Do not return anything, modify nums1 in-place instead.\n */\nvar merge = function (nums1, m, nums2, n) {\n    let i = m - 1;        // last element of nums1\n    let j = n - 1;        // last element of nums2\n    let k = m + n - 1;    // last position of nums1\n\n    while (j >= 0) {\n        if (i >= 0 && nums1[i] > nums2[j]) {\n            nums1[k] = nums1[i];\n            i--;\n        } else {\n            nums1[k] = nums2[j];\n            j--;\n        }\n        k--;\n    }\n};\n"
    },
    {
      "id": "0094",
      "title": "Binary Tree Inorder Traversal",
      "difficulty": "Easy",
      "file": "Easy/0094_BinaryTreeInorderTraversal.js",
      "content": "/**\n * Problem #94: Binary Tree Inorder Traversal\n * \n * Given the root of a binary tree, return the inorder traversal of its nodes' values.\n * \n * Example 1:\n * Input: root = [1,null,2,3]\n * Output: [1,3,2]\n * \n * Example 2:\n * Input: root = []\n * Output: []\n * \n * Example 3:\n * Input: root = [1]\n * Output: [1]\n * \n * Constraints:\n * - The number of nodes in the tree is in the range [0, 100].\n * - -100 <= Node.val <= 100\n */\n\n/**\n * Definition for a binary tree node.\n * function TreeNode(val, left, right) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.left = (left===undefined ? null : left)\n *     this.right = (right===undefined ? null : right)\n * }\n */\n\n/**\n * @param {TreeNode} root\n * @return {number[]}\n */\nvar inorderTraversal = function (root) {\n    let result = [];\n\n    /**\n     * Helper function for recursive depth-first search\n     */\n    var dfs = function (node) {\n        if (node === null) return;\n        \n        // Traverse left subtree\n        dfs(node.left);\n        \n        // Visit root node\n        result.push(node.val);\n        \n        // Traverse right subtree\n        dfs(node.right);\n    }\n    \n    dfs(root);\n    return result;\n};\n"
    },
    {
      "id": "0100",
      "title": "Same Tree",
      "difficulty": "Easy",
      "file": "Easy/0100_SameTree.js",
      "content": "/**\n * Problem #100: Same Tree\n * \n * Given the roots of two binary trees p and q, write a function to check if they are the same or not.\n * Two binary trees are considered the same if they are structurally identical, and the nodes have the same value.\n * \n * Example 1:\n * Input: p = [1,2,3], q = [1,2,3]\n * Output: true\n * \n * Example 2:\n * Input: p = [1,2], q = [1,null,2]\n * Output: false\n * \n * Example 3:\n * Input: p = [1,2,1], q = [1,1,2]\n * Output: false\n * \n * Constraints:\n * - The number of nodes in both trees is in the range [0, 100].\n * - -10^4 <= Node.val <= 10^4\n */\n\n/**\n * Definition for a binary tree node.\n * function TreeNode(val, left, right) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.left = (left===undefined ? null : left)\n *     this.right = (right===undefined ? null : right)\n * }\n */\n\n/**\n * @param {TreeNode} p\n * @param {TreeNode} q\n * @return {boolean}\n */\nvar isSameTree = function (p, q) {\n    // If both nodes are null, the trees are the same at this position\n    if (!p && !q) return true;\n    \n    // If one node is null and the other is not, they are different\n    if (!p || !q) return false;\n\n    // If values are different, they are different\n    if (p.val != q.val) return false;\n\n    // Recursively check left and right subtrees\n    return isSameTree(p.left, q.left) && isSameTree(p.right, q.right);\n};\n"
    },
    {
      "id": "0101",
      "title": "Symmetric Tree",
      "difficulty": "Easy",
      "file": "Easy/0101_SymmetricTree.js",
      "content": "/**\n * Problem #101: Symmetric Tree\n * \n * Given the root of a binary tree, check whether it is a mirror of itself (i.e., symmetric around its center).\n * \n * Example 1:\n * Input: root = [1,2,2,3,4,4,3]\n * Output: true\n * \n * Example 2:\n * Input: root = [1,2,2,null,3,null,3]\n * Output: false\n * \n * Constraints:\n * - The number of nodes in the tree is in the range [1, 1000].\n * - -100 <= Node.val <= 100\n */\n\n/**\n * Definition for a binary tree node.\n * function TreeNode(val, left, right) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.left = (left===undefined ? null : left)\n *     this.right = (right===undefined ? null : right)\n * }\n */\n\n/**\n * @param {TreeNode} root\n * @return {boolean}\n */\nvar isSymmetric = function (root) {\n    if (!root) return true;\n\n    /**\n     * Helper function to check if two subtrees are mirrors of each other\n     */\n    let isMirror = function (left, right) {\n        // Both nodes are null\n        if (left == null && right == null) return true;\n        \n        // Only one node is null or values differ\n        if (!left || !right) return false;\n        if (left.val != right.val) return false;\n        \n        // Check if outer children and inner children are mirrors\n        return isMirror(left.left, right.right) && isMirror(left.right, right.left);\n    }\n\n    return isMirror(root.left, root.right);\n};\n"
    }
  ],
  "Medium": [
    {
      "id": "2",
      "title": "Add Two Numbers",
      "difficulty": "Medium",
      "file": "Medium/0002_AddTwoNumbers.js",
      "content": "/**\n * Problem #2: Add Two Numbers (Medium)\n * \n * You are given two non-empty linked lists representing two non-negative integers. \n * The digits are stored in reverse order, and each of their nodes contains a single digit. \n * Add the two numbers and return the sum as a linked list.\n * \n * You may assume the two numbers do not contain any leading zero, except the number 0 itself.\n * \n * Example 1:\n * Input: l1 = [2,4,3], l2 = [5,6,4]\n * Output: [7,0,8]\n * Explanation: 342 + 465 = 807.\n * \n * Example 2:\n * Input: l1 = [0], l2 = [0]\n * Output: [0]\n * \n * Example 3:\n * Input: l1 = [9,9,9,9,9,9,9], l2 = [9,9,9,9]\n * Output: [8,9,9,9,0,0,0,1]\n * \n * Constraints:\n * - The number of nodes in each linked list is in the range [1, 100].\n * - 0 <= Node.val <= 9\n * - It is guaranteed that the list represents a number that does not have leading zeros.\n */\n\n/**\n * Definition for singly-linked list.\n * function ListNode(val, next) {\n *     this.val = (val===undefined ? 0 : val)\n *     this.next = (next===undefined ? null : next)\n * }\n */\n\n/**\n * @param {ListNode} l1\n * @param {ListNode} l2\n * @return {ListNode}\n */\nvar addTwoNumbers = function (l1, l2) {\n    let dummy = new ListNode(0);\n    let current = dummy;\n    let carry = 0;\n\n    while (l1 || l2 || carry > 0) {\n        let val1 = l1 ? l1.val : 0;\n        let val2 = l2 ? l2.val : 0;\n        let sum = val1 + val2 + carry;\n\n        // Calculate carry for the next sum\n        carry = Math.floor(sum / 10);\n        \n        // Create new node with the current digit\n        current.next = new ListNode(sum % 10);\n        current = current.next;\n        \n        // Advance the pointers\n        l1 = l1 ? l1.next : null;\n        l2 = l2 ? l2.next : null;\n    }\n    \n    return dummy.next;\n};\n"
    },
    {
      "id": "3",
      "title": "Longest Substring Without Repeating Characters",
      "difficulty": "Medium",
      "file": "Medium/0003_LongestSubstringWithoutRepeatingCharacters.js",
      "content": "/**\n * Problem #3: Longest Substring Without Repeating Characters (Medium)\n * \n * Given a string s, find the length of the longest substring without repeating characters.\n * \n * Example 1:\n * Input: s = \"abcabcbb\"\n * Output: 3\n * Explanation: The answer is \"abc\", with the length of 3.\n * \n * Example 2:\n * Input: s = \"bbbbb\"\n * Output: 1\n * \n * Example 3:\n * Input: s = \"pwwkew\"\n * Output: 3\n * Explanation: The answer is \"wke\", with the length of 3.\n * \n * Constraints:\n * - 0 <= s.length <= 5 * 10^4\n * - s consists of English letters, digits, symbols and spaces.\n * \n * ---\n * ### Execution Flow Table (Example: s = \"pwwkew\")\n * \n * | Step | Char | Start | i | Action | charSet | maxLength |\n * | :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n * | 0 | 'p' | 0 | 0 | Add 'p' | {p} | 1 |\n * | 1 | 'w' | 0 | 1 | Add 'w' | {p, w} | 2 |\n * | 2 | 'w' | 0 | 2 | Duplicate 'w'! Shrink window | {p, w} -> {w} | 2 |\n * | 3 | 'k' | 2 | 3 | Add 'k' | {w, k} | 2 |\n * | 4 | 'e' | 2 | 4 | Add 'e' | {w, k, e} | 3 |\n * | 5 | 'w' | 2 | 5 | Duplicate 'w'! Shrink window | {k, e, w} | 3 |\n */\n\n/**\n * @param {string} s\n * @return {number}\n */\nvar lengthOfLongestSubstring = function (s) {\n    if (s.length < 2) return s.length;\n\n    let maxLength = 0;\n    let start = 0;\n    let charSet = new Set();\n\n    for (let i = 0; i < s.length; i++) {\n        // Sliding Window logic: \n        // If we find a duplicate, shrink the window from the left\n        while (charSet.has(s[i])) {\n            charSet.delete(s[start]);\n            start++;\n        }\n        \n        // Add current character and calculate max length\n        charSet.add(s[i]);\n        maxLength = Math.max(maxLength, i - start + 1);\n    }\n    \n    return maxLength;\n};\n"
    },
    {
      "id": "5",
      "title": "Longest Palindromic Substring",
      "difficulty": "Medium",
      "file": "Medium/0005_LongestPalindromicSubstring.js",
      "content": "/**\n * Problem #5: Longest Palindromic Substring (Medium)\n * \n * Given a string s, return the longest palindromic substring in s.\n * \n * Example 1:\n * Input: s = \"babad\"\n * Output: \"bab\"\n * Explanation: \"aba\" is also a valid answer.\n * \n * Example 2:\n * Input: s = \"cbbd\"\n * Output: \"bb\"\n * \n * Constraints:\n * - 1 <= s.length <= 1000\n * - s consists of only digits and English letters.\n * \n * ---\n * ### Execution Flow Table (Example: s = \"babad\")\n * \n * | Step | Index | Char | Expand (Odd) | Expand (Even) | Found Palindrome | State (Start, End) | Substring |\n * | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n * | 0 | 0 | 'b' | \"b\" (1) | \"\" (0) | \"b\" | (0, 0) | \"b\" |\n * | 1 | 1 | 'a' | \"bab\" (3) | \"\" (0) | \"bab\" | (0, 2) | \"bab\" |\n * | 2 | 2 | 'b' | \"aba\" (3) | \"\" (0) | \"aba\" (equal len) | (0, 2) | \"bab\" |\n * | 3 | 3 | 'a' | \"a\" (1) | \"\" (0) | - | (0, 2) | \"bab\" |\n * | 4 | 4 | 'd' | \"d\" (1) | \"\" (0) | - | (0, 2) | \"bab\" |\n * \n * Final Result: \"bab\" (or \"aba\")\n */\n\n/**\n * @param {string} s\n * @return {string}\n */\nvar longestPalindrome = function (s) {\n    if (s.length < 2) return s;\n\n    let start = 0;\n    let end = 0;\n\n    /**\n     * Helper to expand outwards from a center and return the length of the palindrome\n     */\n    let checkAround = function (s, left, right) {\n        while (left >= 0 && right < s.length && s[left] === s[right]) {\n            left--;\n            right++;\n        }\n        // Result is length: right - left - 1\n        return right - left - 1;\n    }\n\n    for (let i = 0; i < s.length; i++) {\n        // Case 1: Centered at i (odd length, e.g. \"aba\")\n        let len1 = checkAround(s, i, i);\n        \n        // Case 2: Centered between i and i+1 (even length, e.g. \"abba\")\n        let len2 = checkAround(s, i, i + 1);\n        \n        // Pick the best of the two\n        let len = Math.max(len1, len2);\n        \n        // Update the best start/end indices if we found a longer one\n        if (len > end - start) {\n            start = i - Math.floor((len - 1) / 2);\n            end = i + Math.floor(len / 2);\n        }\n    }\n\n    return s.slice(start, end + 1);\n};\n"
    },
    {
      "id": "6",
      "title": "Zigzag Conversion",
      "difficulty": "Medium",
      "file": "Medium/0006_ZigzagConversion.js",
      "content": "/**\n * Problem #6: Zigzag Conversion (Medium)\n * \n * The string \"PAYPALISHIRING\" is written in a zigzag pattern on a given number of rows like this:\n * P   A   H   N\n * A P L S I I G\n * Y   I   R\n * \n * And then read line by line: \"PAHNAPLSIIGYIR\"\n * \n * Write the code that will take a string and make this conversion given a number of rows.\n * \n * Example 1:\n * Input: s = \"PAYPALISHIRING\", numRows = 3\n * Output: \"PAHNAPLSIIGYIR\"\n * \n * Example 2:\n * Input: s = \"PAYPALISHIRING\", numRows = 4\n * Output: \"PINALSIGYAHRPI\"  (Wait, original is PINALSIGYAHRPI)\n * \n * Constraints:\n * - 1 <= s.length <= 1000\n * - s consists of English letters (lower-case and upper-case), ',' and '.'.\n * - 1 <= numRows <= 1000\n * \n * ---\n * ### Execution Flow Table (Example: s = \"PAYPAL\", numRows = 3)\n * \n * | Step | s[i] | temp (Row) | direction | arr Status |\n * | :--- | :--- | :---       | :---      | :--- |\n * | 0 | 'P' | 0 | 1 (Down) | `arr[0]=\"P\"` |\n * | 1 | 'A' | 1 | 1 (Down) | `arr[1]=\"A\"` |\n * | 2 | 'Y' | 2 | -1 (Up) | `arr[2]=\"Y\"` (Hit bottom limit) |\n * | 3 | 'P' | 1 | -1 (Up) | `arr[1]=\"AP\"` |\n * | 4 | 'A' | 0 | 1 (Down) | `arr[0]=\"PA\"` (Hit top limit) |\n * | 5 | 'L' | 1 | 1 (Down) | `arr[1]=\"APL\"` |\n * | 6 | -   | - | -        | **Result:** \"PA\" + \"APL\" + \"Y\" = \"PAAPLY\" |\n */\n\n/**\n * @param {string} s\n * @param {number} numRows\n * @return {string}\n */\nvar convert = function (s, numRows) {\n    if (numRows === 1) return s;\n    let arr = [];\n    let direction = 1; // -1->up  1->down \n    let temp = 0;\n\n    for (let i = 0; i < s.length; i++) {\n        if (!arr[temp]) arr[temp] = \"\";\n        arr[temp] = arr[temp] + s[i];\n        temp += direction;\n        if (temp === 0 || temp === numRows - 1) {\n            direction *= -1;\n        }\n    }\n\n    return arr.join(\"\");\n};\n"
    },
    {
      "id": "7",
      "title": "Reverse Integer",
      "difficulty": "Medium",
      "file": "Medium/0007_ReverseInteger.js",
      "content": "/**\n * Problem #7: Reverse Integer (Medium)\n * \n * Given a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range [-2^31, 2^31 - 1], then return 0.\n * \n * Assume the environment does not allow you to store 64-bit integers (signed or unsigned).\n * \n * Example 1:\n * Input: x = 123\n * Output: 321\n * \n * Example 2:\n * Input: x = -123\n * Output: -321\n * \n * Example 3:\n * Input: x = 120\n * Output: 21\n * \n * Constraints:\n * - -2^31 <= x <= 2^31 - 1\n * \n * ---\n * ### Execution Flow Table (Example: x = 123)\n * \n * | Step | result | temp | temp % 10 | Action |\n * | :--- | :--- | :--- | :--- | :--- |\n * | 0 | 0 | 123 | - | Initialize variables |\n * | 1 | 3 | 12 | 3 | Add 3 to result |\n * | 2 | 32 | 1 | 2 | Add 2 to result |\n * | 3 | 321 | 0 | 1 | Add 1 to result |\n * | 4 | 321 | 0 | - | Return result (in bounds) |\n */\n\n/**\n * @param {number} x\n * @return {number}\n */\nvar reverse = function (x) {\n    let result = 0;\n    let temp = x;\n    while (temp) {\n        result = result * 10 + (temp % 10);\n        temp = Math.trunc(temp / 10);\n    }\n    if (result > 2147483647 || result < -2147483648) return 0;\n    return result;\n};\n"
    },
    {
      "id": "8",
      "title": "String to Integer",
      "difficulty": "atoi",
      "file": "Medium/0008_StringToIntegerAtoi.js",
      "content": "/**\n * Problem #8: String to Integer (atoi) (Medium)\n * \n * Implement the myAtoi(string s) function, which converts a string to a 32-bit signed integer (similar to C/C++'s atoi function).\n * \n * The algorithm for myAtoi(string s) is as follows:\n * 1. Read in and ignore any leading whitespace.\n * 2. Check if the next character (if not already at the end of the string) is '-' or '+'. Read this character in if it is either. This determines if the final result is negative or positive respectively. Assume the result is positive if neither is present.\n * 3. Read in next the characters until the next non-digit character or the end of the input is reached. The rest of the string is ignored.\n * 4. Convert these digits into an integer (i.e. \"123\" -> 123, \"0032\" -> 32). If no digits were read, then the integer is 0. Change the sign as necessary (from step 2).\n * 5. If the integer is out of the 32-bit signed integer range [-2^31, 2^31 - 1], then clamp the integer so that it remains in the range. Specifically, integers less than -2^31 should be clamped to -2^31, and integers greater than 2^31 - 1 should be clamped to 2^31 - 1.\n * 6. Return the integer as the final result.\n * \n * Example 1:\n * Input: s = \"42\"\n * Output: 42\n * \n * Example 2:\n * Input: s = \"   -42\"\n * Output: -42\n * \n * Example 3:\n * Input: s = \"4193 with words\"\n * Output: 4193\n * \n * Constraints:\n * - 0 <= s.length <= 200\n * - s consists of English letters (lower-case and upper-case), digits (0-9), ' ', '+', '-', and '.'.\n * \n * ---\n * ### Execution Flow Table (Example: s = \"   -42\")\n * \n * | Step | s[i] | Phase          | result | isN |\n * | :--- | :--- | :---           | :---   | :--- |\n * | 0 | ' ' | Ignore spaces  | 0 | 1 |\n * | 1 | '-' | Sign Check     | 0 | -1 |\n * | 2 | '4' | Parsing Digits | 4 | -1 |\n * | 3 | '2' | Parsing Digits | 42 | -1 |\n * | 4 | -   | Complete       | 42 | -1 | => Result: -42\n */\n\n/**\n * @param {string} s\n * @return {number}\n */\nvar myAtoi = function (s) {\n    let result = 0;\n    let i = 0;\n    let isN = 1;\n    while (s[i] === \" \") {\n        i++;\n    }\n    if (s[i] == \"-\" || s[i] == \"+\") {\n        if (s[i] == \"-\") isN = -1;\n        i++;\n    }\n\n    while (s[i] >= \"0\" && s[i] <= \"9\") {\n        result = result * 10 + +s[i];\n        i++;\n    }\n\n    // Clamp the integer bounding\n    if (result > 2147483647 || result < -2147483648) {\n        if (isN > 0) return 2147483647;\n        else return -2147483648;\n    }\n    \n    return result * isN;\n};\n"
    }
  ],
  "Hard": []
};
const JOURNAL_DATA = [
  {
    "title": "Day 4: March 30, 2026",
    "content": "**Problems Solved:** 3 ([#6](file:///e:/LeetCode/Medium/0006_ZigzagConversion.js), [#7](file:///e:/LeetCode/Medium/0007_ReverseInteger.js), [#8](file:///e:/LeetCode/Medium/0008_StringToIntegerAtoi.js))\n\n**Experience & Learning:**\n- **String & Array Manipulation**: Tackled \"Zigzag Conversion,\" manipulating rows and arrays using a bidirectional pointer (`direction`). It was a clever way to simulate downward and upward diagonal reads without complex 2D matrices.\n- **Integer Manipulation**: Solved two classic medium problems: \"Reverse Integer\" and \"String to Integer (atoi)\". Both of these required careful consideration of 32-bit signed integer boundaries (`-2147483648` to `2147483647`).\n- **Edge Cases**: In `atoi`, I learned that string parsing problems are 90% edge-cases. Dealing with leading whitespaces, negative/positive signs, correctly stopping at non-digit characters, and bounding the final result really reinforced the importance of step-by-step state tracking.\n- **Milestone**: Reached **26 total problems solved**! Finding a steady rhythm with Medium-difficulty challenges.\n\n*\"Building the future of enterprise software, one line of code at a time.\"*"
  },
  {
    "title": "Day 3: March 29, 2026",
    "content": "**Problems Solved:** 7 ([#70](file:///e:/LeetCode/Easy/0070_ClimbingStairs.js), [#94](file:///e:/LeetCode/Easy/0094_BinaryTreeInorderTraversal.js), [#100](file:///e:/LeetCode/Easy/0100_SameTree.js), [#101](file:///e:/LeetCode/Easy/0101_SymmetricTree.js), [#2](file:///e:/LeetCode/Medium/0002_AddTwoNumbers.js), [#3](file:///e:/LeetCode/Medium/0003_LongestSubstringWithoutRepeatingCharacters.js), [#5](file:///e:/LeetCode/Medium/0005_LongestPalindromicSubstring.js))\n\n**Experience & Learning:**\n- **Dynamic Programming (DP)**: Solved \"Climbing Stairs,\" which is a classic introduction to DP. It was interesting to see how the problem breaks down into smaller sub-problems. It's essentially the Fibonacci sequence where each step is the sum of the ways to reach the two previous steps. \n- **Tree Structures**: Added \"Binary Tree Inorder Traversal,\" \"Same Tree,\" and \"Symmetric Tree.\" These problems highlighted the power of **Recursion** for traversing and comparing hierarchical structures. The \"mirror image\" logic for symmetry was a direct extension of the \"same tree\" comparison.\n- **Sliding Window**: Mastered the **Sliding Window** technique with \"Longest Substring Without Repeating Characters.\" Using a `Set` to track the current unique sequence and shrinking the window from the left is an elegant solution to an $O(n)$ problem.\n- **Expand Around Center**: Solved \"Longest Palindromic Substring\" by expanding from each character (odd length) and each gap between characters (even length). This is an intuitive $O(n^2)$ solution that reinforces symmetry concepts from the earlier tree problems. \n- **Milestone 23**: Reached a total of **23 problems solved**. Today has been incredibly productive with a strong mix of Easy and Medium problems, plus a major repository cleanup!\n\n---"
  },
  {
    "title": "Day 2: March 27, 2026",
    "content": "**Problems Solved:** 10 ([#26](file:///e:/LeetCode/Easy/0026_RemoveDuplicatesFromSortedArray.js), [#27](file:///e:/LeetCode/Easy/0027_RemoveElement.js), [#28](file:///e:/LeetCode/Easy/0028_FindIndexFirstOccurrence.js), [#35](file:///e:/LeetCode/Easy/0035_SearchInsertPosition.js), [#58](file:///e:/LeetCode/Easy/0058_LengthOfLastWord.js), [#66](file:///e:/LeetCode/Easy/0066_PlusOne.js), [#67](file:///e:/LeetCode/Easy/0067_AddBinary.js), [#69](file:///e:/LeetCode/Easy/0069_SqrtX.js), [#83](file:///e:/LeetCode/Easy/0083_RemoveDuplicatesFromSortedList.js), [#88](file:///e:/LeetCode/Easy/0088_MergeSortedArray.js))\n\n**Experience & Learning:**\n...\n- **In-Place Merging**: Mastered the technique of merging two sorted arrays in-place by iterating backwards. This prevents overwriting data in the first array and is highly efficient (O(1) space).\n- **Consistency**: Reached **16 total problems solved**! Today has been legendary with 10 new solutions documented in a single day.\n\n---"
  },
  {
    "title": "Day 1: March 26, 2026",
    "content": "**Problems Solved:** 6 ([#1](file:///e:/LeetCode/Easy/0001_TwoSum.js), [#9](file:///e:/LeetCode/Easy/0009_PalindromeNumber.js), [#13](file:///e:/LeetCode/Easy/0013_RomanToInteger.js), [#14](file:///e:/LeetCode/Easy/0014_LongestCommonPrefix.js), [#20](file:///e:/LeetCode/Easy/0020_ValidParentheses.js), [#21](file:///e:/LeetCode/Easy/0021_MergeTwoSortedLists.js))\n\n**Experience & Learning:**\n- **Project Structure**: Set up the foundational structure for this repository, organizing problems by difficulty and implementing an automated progress tracking system via `README.md` files.\n- **Core Algorithms**: Tackled fundamental problems involving hash maps (Two Sum), string manipulation (Longest Common Prefix, Valid Parentheses), and math (Roman to Integer, Palindrome Number).\n- **Portfolio Integration**: Linked this repository to my main GitHub portfolio and added dynamic stats cards to showcase my progress.\n- **Git Workflow**: Established a clean workflow for committing and pushing solutions with appropriate documentation."
  }
];